- kernel/patches/5.10.0/0001-bpf-sockmap-add-extra-return-value-for-sockops.patch
- kernel/patches/5.10.0/0002-net-ipv4-A-new-bit-is-added-to-indicate-whether-to-d.patch
- kernel/patches/5.10.0/0003-ipv4-bpf-Introduced-to-support-the-ULP-to-modify.patch
- kernel/patches/5.10.0/0004-net-bpf-Add-a-writeable_tracepoint-to-inet_stream_co.patch
- kernel/patches/5.10.0/0005-bpf-Introduces-a-new-state-to-identify-the-location-.patch
- kernel/patches/5.10.0/0006-bpf-Introduce-the-string-processing-helper.patch
- kernel/patches/5.10.0/0007-bpf-add-strncmp-helper-function.patch
- kernel/patches/5.10.0/0008-bpf-Two-helper-functions-are-introduced-to-parse-use.patch
Compared to the previous implementation of kmesh on oe2203, the kernel side implementation of kmesh has been adjusted to use ULP framework and the replylong parameter has been used，etc. so,we need update kernel patches.
> kernel:update the kmesh feature patches for kernel-5.10

- Makefile
- bpf/include/common.h
- bpf/kmesh/cgroup_sock.c
- bpf/kmesh/include/kmesh_common.h
- build.sh
- config/kmesh_marcos_def.h
- kernel/ko_src/Makefile
- kmesh_macros_env.sh
- pkg/bpf/bpf_kmesh.go
- pkg/bpf/bpf_kmesh_common.go
- pkg/bpf/bpf_kmesh_l4.go
A new compilation macro, ISKERNEL_ENHANCED, has been introduced to determine whether the current running environment is an enhanced kernel.
On an enhanced kernel, all capabilities of kmesh are supported. On a non-enhanced kernel, only the L4 proxy capability of kmesh is supported.
To implement these capabilities, the following modifications have been made to the code:
1、Code that cannot be compiled or run due to kernel dependencies is included using compilation macros. For Go code, file-level conditional compilation is used. A new file bpf_kmesh_l4.go has been added, which is derived from the bpf_kmesh.go file by removing the parts of the code that depend on the enhanced kernel. add bpf_kmesh_common.go，it is L4 common function.
2、The compilation script does not compile or load kmesh.ko. …
> support tcp proxy independent without kernel enhanced

- build.sh
1、In Ubnutu the default shell (sh) for executing scripts is not bash, enforce it to be bash. 
2、In Ubuntu ，files for the x86_64 architecture such as asm are located in the /usr/include/x86_64-linux-gnu directory, add it to the default include directory for C.
> fix ubuntu  environments compile errors

- config/kmesh_marcos_def.h
- kmesh_macros_env.sh
- oncn-mda/ebpf_src/sock_ops.c
1、Merge duplicate semantic macro definitions.
2、Optimize the logic of the macro build script. Determine the feature capabilities supported by the current environment during compilation, and then set the values of the macros accordingly.
> kmesh marcos optimization

- bpf/kmesh/include/kmesh_common.h
in  unenhanced kernel 5.10, build reports the following error
Compiled /root/zmy/github/1103/kmesh/bpf/kmesh/bpf2go/kmeshcgroupsock_bpfel.o
Stripped /root/zmy/github/1103/kmesh/bpf/kmesh/bpf2go/kmeshcgroupsock_bpfel.o
Error: can't write /root/zmy/github/1103/kmesh/bpf/kmesh/bpf2go/kmeshcgroupsock_bpfel.go: can't load BPF from ELF: section "cgroup/connect4": string is not stack allocated: not supported
exit status 1
bpf/kmesh/bpf2go/bpf2go.go:24: running "go": exit status 1
make: *** [Makefile:39: all] Error 1
Some syntax is not supported in this kernel version, modify the syntax.
> fix can't load BPF from ELF

- bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
In the Ubuntu environment, a message is displayed indicating that the map data fails to be updated during the Kmesh test in the Istio cluster deployed using Kind.
Reason:
1. When the xds configuration is converted to bpf map data, the deserial_update_elem-> get_map_fd_info -> bpf_obj_get_info_by_fd returns - 1 and errno is - 7.
2. Trace the bpf_obj_get_info_by_fd system call. If the value of bpf_obj_get_info_by_fd-> bpf_map_get_info_by_fd -> bpf_check_uarg_tail_zero -> check_zeroed_user is not 0, an error is reported when the input parameter buffer is not all 0s.
Analyze the invoking point. It is found that the input variable struct bpf_map_info is not initialized.
Modification scheme:
The code is checked and variable initialization is performed in a unified manner.
> fix the issue of failure to update bpf map data in Ubuntu environment

- bpf/kmesh/include/cluster.h
- bpf/kmesh/include/filter.h
- bpf/kmesh/include/kmesh_common.h
- bpf/kmesh/include/listener.h
- bpf/kmesh/include/route_config.h
- bpf/kmesh/include/tail_call.h
- bpf/kmesh/include/tcp_proxy.h
- bpf/kmesh/sockops.c
Optimize the code for invoking the tail-call prog command and unify the return value of the bpf prog command.
1. When the tail-call prog is invoked, the context information needs to be prepared. The macro is encapsulated to prepare the context key and value, and the context update/delete and tail call invoking are encapsulated into a macro to avoid CTX map leakage.
2. The BPF_OK macro is encapsulated.
3. The Kmesh is a data plane acceleration program. When the traffic governance logic fails to be executed, the original forwarding process should be downgraded, and the bpf prog should always return a success message.
> Optimize the code for invoking the tail-call prog command and unify the return value of the bpf prog command.

- test/testcases/kmesh/libs/common.sh
After the Kmesh supports multi-OS version compilation, the Kmesh compiled in the non-enhanced OS environment does not contain the ko file (used in the L7 governance scenario). The mini-test cases related to L4 traffic governance do not need to check whether the ko file is successfully loaded.
> Rectify false positives in L4 test cases

- test/testcases/kmesh/libs/cni.conflist
- test/testcases/kmesh/libs/common.sh
due to kmesh multiple dataplane work, we need to adapt kmesh min-test:
add a cni.conflist and adapt test script, add the test script process to the cgroup net_cls and tag with kmesh
fixes https://github.com/kmesh-net/kmesh/issues/56
> mini-test adapt

- bpf/kmesh/include/kmesh_common.h
- build.sh
- build/docker/kmesh.dockerfile
- build/docker/kmesh.yaml
- kmesh_bpf_env.sh
- kmesh_compile_env_pre.sh
- kmesh_macros_env.sh
1、Obtain the bpf_mem_ptr structure from the ENHANCED_KERNEL macro and determine whether the structure exists in the environment.
2、The logic for obtaining compilation macros is modified so that /usr/include/linux/bpf.h of the host machine can be read in the online compilation environment.
3、kmesh.yaml and kmesh.dockerfile adapted
> support compile online image

- build/docker/kmesh.yaml
The location of the config file varies according to the Kubernetes cluster creation mode. 
You need to specify the location of the config file in the cluster environment. 
Kmesh.yaml In this project, the default location of the config file is /root/.kube/config. Most cluster creation methods place files here
> fix :can't obtain cluster config when image start up

- cniplugin/main.go
- daemon/manager/manager.go
- pkg/cni/chained.go
- pkg/cni/config.go
- pkg/cni/install.go
- pkg/cni/kubeconfig.go
- pkg/cni/plugin/plugin.go
With this patch, kmesh now donot take charge of traffic from sidecar. Even in case, kmesh and sidecar both simultaneously enabled, we now prioritize sidecar. 
Fixes #
```release-note
```
> Donot intercept traffic from sidecar

- pkg/cni/plugin/plugin.go
- pkg/utils/kubeclient.go
`kubernetes.Interface` is a standard interface implemented by `ClientSet`. By using `kubernetes.Interface`, it is easier to use fakeClientSet to implement UT.
> Replaced kubernetes.ClientSet with kubernetes.Interface

- build/docker/start_kmesh.sh
WIth it, when kmesh daemon exit on error, the pod entrypoint process can exit, so this allows k8s to restart the container.
Otherwise, we can see the kmesh daemon pod is still running.
Long term, i think we can add some liveness probe
Fixes #
```release-note
NONE
```
> update kmesh start script to exit when kmesh exit

- kernel/ko_src/kmesh/kmesh_parse_http_1_1.c
/kind bug
Fixed an issue with Kmesh failing to parse HTTP headers. When a field in the HTTP header has an empty value, Kmesh would fail to parse it, leading to routing issues. 
Fixes #https://github.com/kmesh-net/kmesh/issues/186
```release-note
```
> fix kmesh http parse header bug

- build/docker/start_kmesh.sh
In the startup script in the kmesh image, the location of the copied kmesh.ko is incorrect and cannot be loaded later. Fix and adjust the location of kmesh.ko.
Fixes #
```release-note
```
> fix kmesh.ko location

- bpf/kmesh/workload/include/config.h
- bpf/kmesh/workload/sockops_tuple.c
- pkg/cni/plugin/plugin.go
- pkg/cni/plugin/plugin_test.go
Currently, the classid of the cgroup is used to determine whether the pod is managed by Kmesh. However, the classid is inconvenient to use. You need to change the Kubernetes hosting mode from systemd to cgroup. And not all programs can get classid in eBPF. Therefore, a new method is introduced to determine the IP address. When the CNI initializes the pod, the IP address of the pod is written into an eBPF map. In the eBPF, the map is directly read and compared with the obtained IP address to determine whether the IP address is managed by the Kmesh.
Introduce a new method to query whether a pod is managed by Kmesh
Fixes # NA
**Does this PR introduce a …
> Kmesh: Introduce a new method to query whether a pod is managed by Kmesh

- bpf/kmesh/workload/cgroup_sock.c
- bpf/kmesh/workload/include/backend.h
- bpf/kmesh/workload/include/tail_call.h
- bpf/kmesh/workload/sockops_tuple.c
- pkg/bpf/bpf_kmesh_workload.go
Ebpf connect4 program support connect to waypoint if the backend config waypoint ip and port.
Waypoint need dst info to routing, now connect4 can deliver these info to sendmsg ebpf, sendmsg can encode dst info by TLV.
Fixes #
```release-note
```
> Kmesh: Add waypoint support for connect and deliver encoder dst info to sendmsg ebpf

- .gitignore
update gitignore because bpf2go update
> update gitignore because bpf2go update

- pkg/bpf/bpf_kmesh_workload.go
- pkg/bpf/config.go
- pkg/cni/chained.go
- pkg/cni/chained_test.go
- pkg/cni/install.go
- pkg/cni/plugin/plugin.go
- pkg/constants/constants.go
By passing working mode as cni configuration. With this, the config now looks like below:
```
{
"kubeConfig": "/etc/cni/net.d/kmesh-cni-kubeconfig",
"mode": "ads",
"type": "kmesh-cni"
}
```
Fixes #
```release-note
```
> Enable xdp auth when kmesh works in workload mode

- pkg/cache/v2/listener_test.go
- pkg/controller/envoy/ads_event_test.go
- pkg/utils/test/bpf_map.go
Added benchmark test for listener.Flush()
> Added benchmark test for listener.Flush()

- pkg/cache/v2/cluster_test.go
> opt cluster ut test

- bpf/kmesh/workload/cgroup_sock.c
- bpf/kmesh/workload/include/frontend.h
- bpf/kmesh/workload/include/workload.h
- pkg/controller/workload/workload_event.go
- pkg/controller/workload/workload_frontend.go
Fixes #277
```release-note
```
> rename service_id to upstream_id in frontend_value struct

- pkg/controller/client_test.go
add ut of client.go
a part of #104
> add ut of client.go

- .github/workflows/main.yml
This is to enable 
```
merge_group event to trigger your GitHub Actions workflow when a pull request is added to a merge queue.
```
And i have enabled that on github branch protection
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
Fixes #
```release-note
NONE
```
> Enable merge queue

- bpf/kmesh/workload/cgroup_sock.c
- bpf/kmesh/workload/sockops_tuple.c
- oncn-mda/ebpf_src/sock_ops.c
We areusing bpf_map_delete_elem  which returns longs type. We see very weired phenomenon though it is -2 when no key exists, but it is not equal to int -2.
Fixes #
```release-note
```
> FIX bpf_map_delete_elem unexpected error log

- hack/format.sh
fix clang format tool not install
> fix clang format tool not install

- bpf/kmesh/workload/sockops_tuple.c
sockops port is not same as other linux vendor. We need to adapt oe 23.03.
/kind bug
repair issue #298 
Fixes #
https://github.com/kmesh-net/kmesh/issues/298
NA
NA
```release-note
NA
```
> Kmesh: repair kmesh manager not effect in sockops on oe 23.03

- bpf/kmesh/workload/cgroup_sock.c
- bpf/kmesh/workload/include/backend.h
- bpf/kmesh/workload/include/ctx/sock_addr.h
- bpf/kmesh/workload/include/frontend.h
- bpf/kmesh/workload/include/workload.h
- pkg/controller/workload/bpfcache/frontend.go
- pkg/controller/workload/workload_processor.go
Fixes #277
```release-note
```
> remove unnecessary port fields in frontend_key

- pkg/bpf/bpf_kmesh.go
> Fix the Enhanced Compilation Failure Issue

- pkg/cache/v2/cluster_test.go
- pkg/cache/v2/listener_test.go
- pkg/controller/ads/ads_processor_test.go
- pkg/controller/client_test.go
- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
- pkg/utils/test/bpf_map.go
add benchmark of workload
Fixes #
```release-note
```
> add benchmark of workload

- pkg/cache/v2/listener_test.go
A random address is set for the listener in the test case
Fixes #
```release-note
```
> update listener benchmark

- pkg/utils/test/bpf_map.go
/kind bug
Fixes #340 
```release-note
```
> fix bpf-map test failed

- pkg/auth/rbac.go
> fix: should get authz policy from dst-worklod when rbac

- docs/kmesh_development_guide.md
- docs/multiple dataplane_CN.md
- docs/multiple dataplane_EN.md
documentation
Fix some typo errors of some documents.
```release-note
```
> Fix some typo errors of some documents

- pkg/auth/rbac.go
- pkg/controller/ads/ads_processor.go
- pkg/controller/client.go
- pkg/controller/config/config.go
- pkg/controller/config/config_test.go
- pkg/controller/workload/workload_processor.go
…olicy update
Fixes #https://github.com/kmesh-net/kmesh/issues/268
```release-note
```
> use ztunnel-role with workload mode, fix authz policy not work when update

- docs/xds_handle.md
- docs/xds_handle_zh.md
documentation
translate xds_handle.md to Chinese
```release-note
```
> docs: translate xds_handle.md to Chinese

- pkg/controller/ads/cache_test.go
add ut of ads_loader.go
a part of #104
> add ut of ads_loader.go

- bpf/include/bpf_log.h
- bpf/kmesh/ads/cgroup_sock.c
- bpf/kmesh/ads/include/cluster.h
- bpf/kmesh/ads/include/filter.h
- bpf/kmesh/ads/include/kmesh_common.h
- bpf/kmesh/ads/include/listener.h
- bpf/kmesh/ads/include/route_config.h
- bpf/kmesh/ads/sockops.c
- bpf/kmesh/workload/cgroup_sock.c
- bpf/kmesh/workload/include/backend.h
- bpf/kmesh/workload/include/workload_common.h
- bpf/kmesh/workload/xdp.c
- pkg/controller/controller.go
/kind feature 
Improve ipaddr format of bpf log.
And Fix xdsClient workloadController nil pointer bug  when Kmesh mode is Ads.
Fixes  [358](https://github.com/kmesh-net/kmesh/issues/358)
In ads mode:
In workload mode:
```release-note
```
> Improve bpf log and bugs fix

- pkg/cni/chained.go
- pkg/cni/install.go
/kind bug
Fix cleanup kmesh-cni failed bug.
Fixes  #365 
```release-note
```
> Fix cleanup kmesh-cni failed bug

- bpf/include/bpf_common.h
- bpf/kmesh/ads/cgroup_sock.c
- bpf/kmesh/workload/cgroup_sock.c
- bpf/kmesh/workload/sockops_tuple.c
- pkg/controller/bypass/bypass_controller.go
This PR introduces the implementation of the bypass kmesh function and reuses the map_of_manager table.
If the map contains pod data and the value of the corresponding record is 0, the traffic of the current pod is managed by kmesh.
If the map contains pod data and the value of the corresponding record is 1, the traffic of the current pod is bypassed.
Fixes #
```shell
root@ubuntu-1:~# kubectl get pods -A -owide
NAMESPACE            NAME                                            READY   STATUS    RESTARTS   AGE     IP            NODE                    NOMINATED NODE   READINESS GATES
default              fortio-client-deployment-6966bf9488-h8wmz …
```
> add bypass logic for kmesh

- bpf/kmesh/workload/include/backend.h
- bpf/kmesh/workload/include/endpoint.h
- bpf/kmesh/workload/include/frontend.h
- bpf/kmesh/workload/include/service.h
- bpf/kmesh/workload/include/workload.h
- pkg/controller/workload/bpfcache/backend.go
- pkg/controller/workload/bpfcache/service.go
- pkg/controller/workload/workload_processor.go
1.fix potential target port modify error when access backend directly
2.fix a backend that belongs to multi services
3.store waypoint info in service to accelerate waypoint access
Fixes #
```release-note
```
> some workload mode bugfix and waypoint optimization

- Makefile
enhancement
Sometimes user may interrupt the `make build`(or `make docker`) process, during which a temp docker container named "kmesh-build" will be created. The next time the user `make build`, it will raise an error like 'container kmesh-build already exists'. 
Users should be able to remove `kmesh-build` docker container using `make clean`.
```release-note
```
> Clean kmesh build docker container in make clean

- bpf/include/bpf_common.h
- bpf/include/common.h
- bpf/kmesh/ads/sockops.c
- bpf/kmesh/workload/include/backend.h
- bpf/kmesh/workload/sockops.c
- oncn-mda/ebpf_src/sock_ops.c
- oncn-mda/include/mesh_accelerate.h
Current Situation:
bpf_sock_addr:user_port is stored in u16 network order.
bpf_sock_ops:local_port is stored in u32 host order.
bpf_sock_ops:remote_port oe23.03 is stored in u16 network order, while non-oe23.03 is stored in u32 network order.
Currently, the port conversion is scattered throughout the code and not handled consistently.
Proposed Solution:
Treat all ports as u16.
Maintain the byte order as defined originally.
Provide dedicated macros to retrieve the remote_port and local_port of skops.
Fixes https://github.com/kmesh-net/kmesh/issues/374
```release-note
```
> unified handing logic for skops->remote_port/local_port

- Makefile
add bpf/include/bpf_helper_defs_ext.h to temp files for recovery on make clean
Fixes #
```release-note
```
> update make clean

- deploy/helm/templates/l7-envoyfilter.yaml
- deploy/yaml/l7-envoyfilter.yaml
use `peer_metadata` http filter to get pod metadata from istiod
So we could get necessary fields to fill observability information
**Before this modification, the metric is :**
istio_requests_total{reporter="destination",source_workload="unknown",source_canonical_service="unknown",source_canonical_revision="latest",source_workload_namespace="unknown",source_principal="unknown",source_app="unknown",source_version="unknown",source_cluster="unknown",destination_workload="reviews-v1",destination_workload_namespace="default",destination_principal="unknown",destination_app="unknown",destination_version="unknown",destination_service="reviews.default.svc.cluster.local",destination_canonical_service="reviews",des …
> use peer_metadata to get pod metadata info from istiod

- api/v2/workloadapi/workload_helper.go
- daemon/manager/manager.go
- pkg/controller/workload/cache/service_cache.go
- pkg/controller/workload/workload_processor.go
- pkg/status/api.go
- pkg/status/status_server.go
- pkg/status/status_server_test.go
- pkg/status/testdata/workload_configdump.json
> Support service dump

- bpf/kmesh/workload/include/endpoint.h
- bpf/kmesh/workload/include/service.h
- pkg/controller/workload/workload_processor.go
/kind bug
In istio 1.22.1, when delete a waypoint, which proxy for a certain k8s service, the workload_processor don't update kmesh_service bpf map, end up to still route to the old waypoint.
Fixes #406
```release-note
```
> Fix bug when delete waypoint, dont update bpf kmesh_service map

- daemon/manager/manager.go
- daemon/options/options.go
- daemon/options/secret_manager.go
- pkg/controller/controller.go
- pkg/controller/security/caclient.go
- pkg/controller/security/manager.go
- pkg/controller/security/option.go
- pkg/controller/workload/workload_processor.go
It does many enhancements:
1. added a flag `enable-secret-manager` to allow turn off secret manager
2. Add a separate `retry` fetching cert
3. Removed reconnect, actually grpc connection can be reconnected automatically when the underlying connection closed.
Fixes #
```release-note
```
> Improve security manager

- deploy/helm/templates/daemonset.yaml
- deploy/yaml/kmesh.yaml
- pkg/controller/bypass/bypass_controller.go
> Mount proc

- bpf/include/bpf_log.h
- bpf/include/common.h
- bpf/kmesh/ads/cgroup_sock.c
- bpf/kmesh/ads/include/cluster.h
- bpf/kmesh/ads/include/filter.h
- bpf/kmesh/ads/include/listener.h
- bpf/kmesh/ads/include/route_config.h
- bpf/kmesh/ads/sockops.c
- bpf/kmesh/workload/cgroup_sock.c
- bpf/kmesh/workload/include/backend.h
- bpf/kmesh/workload/include/frontend.h
- bpf/kmesh/workload/include/service.h
- bpf/kmesh/workload/xdp.c
- config/kmesh_marcos_def.h
- daemon/manager/manager.go
- daemon/options/bpf.go
- deploy/helm/values.yaml
- kmesh_macros_env.sh
- pkg/bpf/bpf_kmesh.go
- pkg/constants/constants.go
- pkg/controller/controller.go
- pkg/logger/logger.go
- pkg/status/status_server.go
/kind feature
1. Kmesh eBPF log user space dumping.
version > 5.13 dump bpf log to userspace, otherwise print log in trace pipe.
2. Support dynamic bpf log level.
`k exec ds/kmesh -n kmesh-system -- curl -s localhost:15200/debug/bpfLogLevel/3`
Fixes [388](https://github.com/kmesh-net/kmesh/issues/388)
When print bpf log to kmesh daemon process or user space,  just use BPF_LOG_U instead of BPF_LOG, the args which input is same as BPF_LOG.
```release-note
```
> Kmesh eBPF log user space dumping

- docs/proposal/e2e.md
Fix the chore that the E2E command line flags shows no line breaks when reading from github page.
Fixes #
```release-note
```
> fix display error of e2e flags

- go.mod
- pkg/controller/workload/workload_hash.go
- pkg/controller/workload/workload_hash_test.go
bug
Fixes #479 
```release-note
```
> fix hash name bug (#479)

- daemon/manager/manager.go
- pkg/bpf/bpf.go
- pkg/bpf/bpf_kmesh_l4_workload.go
- pkg/status/status_server.go
/kind bug
Fixes https://github.com/kmesh-net/kmesh/issues/477
```
[root@master ~]#  kubectl exec -it nettool -- curl helloworld-d.default.svc.cluster.local:5000/hello
Hello version: v2, instance: helloworld-v2-654d97458-pmxk6
```
```
time="2024-07-03T12:44:55Z" level=info msg="[KMESH] DEBUG: bpf find listener addr=[10.104.111.255:5000]\n" subsys=ebpf
time="2024-07-03T12:44:55Z" level=info msg="[CLUSTER] INFO: cluster=\"outbound|5000||helloworld.default.svc.cluster.local\", loadbalance to addr=[172.16.219.112:5000]\n" subsys=ebpf
```
```release-note
```
> Fix bpfloglevel update error bug in Ads mode.

- test/e2e/baseline_test.go
- test/e2e/run_test.sh
/kind bug
E2E test case `TestTrafficSplit` was previously incomplete as it was found to be unstable during test.
Now find reason is that if the test application is deployed before Kmesh Ready, it will not managed by Kmesh.
The solution is to ensure Kmesh runs successfully before proceeding with the subsequent steps.
Fixes #
```release-note
```
> fix flaky e2e test

- pkg/status/OWNERS
@Okabe-Rintarou-0 has been working around status server for a while, and is quite familiar with this package. I think he is qualified to own this pkg.
> Add Okabe-Rintarou-0 to pkg/status owners

- pkg/constants/constants.go
- pkg/controller/manage/kmesh_manage.go
Support ns manage after kmesh restart
Fixes #
```release-note
```
Managing Pods in namespace level
```shell
kubectl label ns default istio.io/dataplane-mode=Kmesh
kubectl delete pods --all -n default
kubectl get pods -A -owide
NAMESPACE            NAME                                            READY   STATUS    RESTARTS      AGE     IP            NODE                    NOMINATED NODE   READINESS GATES
default              fortio-client-deployment-7d7f58785b-s4cwc       1/1     Running   0             88m     10.244.1.30   ambient-worker          <none>           <none>
default …
```
> Support ns manage after kmesh restart

- deploy/helm/templates/l7-envoyfilter.yaml
- deploy/yaml/l7-envoyfilter.yaml
To support ipv6, waypoint should listen to both ipv4 and ipv6.
Fixes part of #291
```release-note
```
> waypoint listen both ipv4 and ipv6

- .codecov.yml
- .github/workflows/main.yml
add codecov config
Fixes #
```release-note
```
> add codecov config

- test/e2e/run_test.sh
Now we maintain the latest image of waypoint and also support mulit arch.
So no longer need to include version and arch info.
Fixes #
```release-note
```
> use latest waypoint image to run e2e

- test/e2e/README.md
- test/e2e/baseline_test.go
- test/e2e/main_test.go
- test/e2e/run_test.sh
migrate some waypoint related E2E test cases
Fixes #
```release-note
```
> add some waypoint related E2E test cases

- Makefile
- build/docker/kmesh.dockerfile
- hack/utils.sh
cleanup
remove arch info in build process
Fixes #583 
```release-note
```
> remove arch info in build process

- pkg/controller/bypass/bypass_controller.go
- pkg/controller/manage/kmesh_manage.go
Fixes #597
```release-note
```
> remove resync period

- pkg/dns/dns.go
- pkg/dns/dns_test.go
> Fix DNS cluster's endpoint ip addr check

- docs/kmesh_compile-zh.md
- docs/kmesh_compile.md
- docs/kmesh_deploy_and_develop_in_kind.md
> remove build arch in documents

- .codespellrc
- test/e2e/baseline_test.go
- test/e2e/main_test.go
**What this PR does / why we need it**
e2e tests for waypoint management:
1. Add/remove waypoints at service granularity
2. Add/remove waypoints at namespace granularity
3. Add/remove waypoints at pod granularity
Fixes #
```release-note
```
> E2E test cases for waypoint management

- .github/workflows/e2e-ipv6.yml
- .github/workflows/e2e.yml
- Makefile
- test/e2e/run_test.sh
Support pure ipv6 in e2e test, to fit in the new feature in Kmesh
Fixes #529 
```release-note
```
> Support ipv6 in e2e test

- build/docker/start_kmesh.sh
- daemon/manager/manager.go
- deploy/helm/templates/kmesh-rbac.yaml
- deploy/yaml/clusterrole.yaml
- pkg/bpf/bpf.go
- pkg/bpf/bpf_kmesh_workload.go
- pkg/bpf/bpf_restart.go
- pkg/bpf/bpf_restart_test.go
- pkg/constants/constants.go
- pkg/utils/test/bpf_map.go
/kind feature
Fixes #
```release-note
```
> kmesh support restart by reload old bpf map and prog

- docs/proposal/e2e.md
- test/e2e/run_test.sh
Add two flags to E2E framework:
**--select-cases**: select some cases to run
**--skip-cases**: skip some cases and run others
Fixes #523
```release-note
```
> enable select some e2e cases to run or skip some cases

- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
- pkg/nets/nets.go
- pkg/nets/nets_test.go
> copy bytes optimize

- pkg/utils/enroll.go
- pkg/utils/enroll_test.go
Fixes https://github.com/kmesh-net/kmesh/issues/630
```release-note
```
> preclude pod with host network to be managed by kmesh

- test/e2e/run_test.sh
Enable cleanup in E2E, include cleanup the kind cluster or docker registry or both
Fixes #522
The previous PR was closed because of a bad git action.
```release-note
```
> Enable cleanup in e2e

- build/docker/start_kmesh.sh
- pkg/bpf/bpf_restart.go
- pkg/status/status_server.go
/kind bug
Fixes #646
```release-note
```
> Fix kmesh daemon graceful exit

- pkg/controller/bypass/bypass_controller.go
- pkg/controller/bypass/bypass_test.go
/kind bug
Fixes #
```release-note
```
> Fix TestPodSidecarLabelChangeTriggersAddIptablesAction flake

- build/docker/start_kmesh.sh
- pkg/status/status_server.go
Fixes #654
```release-note
```
> [Release-0.4] Fix kmesh daemon graceful exit

- Makefile
- api/v2-c/Makefile
- bpf/deserialization_to_bpf_map/Makefile
Currently, the binary programs provided by Kmesh lack some necessary secure compilation options during the compilation process. Adding these secure compilation options can effectively prevent some security issues.
Fixes #
@nlgwcy @hzxuzhonghu 
NA
```release-note
```
> add some secure compilation options

- test/e2e/baseline_test.go
- test/e2e/main_test.go
- test/e2e/restart_test.go
- test/e2e/run_test.sh
Add E2E case for that managed applications can work properly before, during and after Kmesh daemon restart
Fixes part of #642
```release-note
```
> e2e test for Kmesh daemon restart

- bpf/include/bpf_log.h
bpf_ringbuffer_output need extra memory copy  FYI https://arthurchiao.art/blog/bpf-ringbuf-zh/
Fixes #
```release-note
```
> Update bpf log

- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/metric_test.go
/kind bug
Fixes #703 
```release-note
```
> fix metric nil pointer panic

- pkg/controller/controller.go
- pkg/controller/manage/manage_controller.go
- pkg/controller/manage/manage_controller_test.go
/kind bug
Link XDP again in deamon, in order to fix Kmesh has restarted but old XDP program remain linked
Fixes #591 #665 
```release-note
NONE
```
> Link XDP again in deamon, in order to fix Kmesh has restarted but old XDP program remain linked

- pkg/bpf/bpf.go
- pkg/bpf/bpf_restart.go
- pkg/constants/constants.go
/kind bug
The current startup strategy of kmesh does not support Update scenarios, so there will be bugs when starting in Update mode. Now the Update startup mode will be forcibly changed to Normal mode, and the Update startup mode will be supported in the future.
Fixes #
```release-note
```
> fix bug that may occur in Update mode

- build/docker/start_kmesh.sh
/kind bug
When starting kmesh, the cgroup directory will be repeatedly created，optimize this
Fixes #
```release-note
```
> fix cgroup mount log

- .codecov.yml
With the hard limit, may even prevent developer from fixing typo, which is not covered before.
> Rm coverage threshold

- pkg/controller/workload/workload_controller_test.go
- pkg/controller/workload/workload_hash.go
- pkg/controller/workload/workload_hash_test.go
- pkg/controller/workload/workload_processor_test.go
…timeout
Without cleaning up hash file, test will fail with timeout error.  By default vs plugin set 30s timeout.
Fixes #
```release-note
```
> FIX: go test timeout after running benchmark test

- test/e2e/run_test.sh
The E2E test will eventually call the `go test` command, which has a variety of flags for adjusting the test.
Obviously, it's very tedious to encapsulate each flag. Therefore we adopt the direct passthrough unknown flags to make full use of existing capabilities of `go test`.
Although it's not very robust, I think it's ok for running test cases.
For example, now we could directly run the follow command:
```bash
./test/e2e/run_test.sh --only-run-tests -run "TestKmeshRestart"  -count 10 -timeout 30m
``` 
Fixes #
```release-note
```
> passthrough go test flag

- pkg/controller/workload/workload_processor.go
/kind bug
cherry-pick
Fixes #751
```release-note
```
> [cherry-pick 0.4] fix depolying ns and service waypoint in mixed manner

- .codecov.yml
Just want codcov to give use a hint, not to block PR merging. Not sure if this works.
Also investigated on prow bot to ignore the codecov, but not found how to congure it
Fixes #
```release-note
```
> Check codecov but not fail github checks

- build/docker/start_kmesh.sh
- daemon/manager/manager.go
- daemon/manager/uninstall/uninstall.go
- pkg/cni/chained.go
- pkg/cni/install.go
Fix option 1 of https://github.com/kmesh-net/kmesh/issues/730
> Do clean up the cni config at the end of https://github.com/kmesh-net/kmesh/blob/main/build/docker/start_kmesh.sh#L54
This may cleanup cni configs twice, but doesnot matter.
If without this, and kmesh crashed unexpected, the k8s cluster will be influenced, the blast radius is very large
Fixes #
```release-note
```
> Improve cni uninstall

- pkg/bpf/bpf_kmesh_workload.go
/kind bug
Fix possible panic in loadKmeshSendmsgObjects
Fixes #
```release-note
```
> Fix possible panic in loadKmeshSendmsgObjects

- pkg/bpf/bpf.go
- pkg/bpf/bpf_kmesh_l4_workload.go
fix verifier log omitted
Fixes #
```release-note
```
> fix verifier log omitted

- test/e2e/baseline_test.go
Fixes #829 
```release-note
```
> increase timeout of bookinfo e2e test

- Makefile
The cgo using gcc to compile *.h files, where the libkmesh_api_v2_c.so using clang which may have conflicts.
```
root@vagrant:/app# docker run -it ghcr.io/kmesh-net/kmesh-build:latest sh
sh-5.2# go env
...
CC='gcc'
CXX='g++'
```
Fixes #702
```release-note
```
> cgo: using CC=clang and CXX=clang++

- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
/kind feature
Fixes [#693](https://github.com/kmesh-net/kmesh/issues/693)
```release-note
```
> Filter out unhealthy workloads

- daemon/manager/manager.go
- pkg/bpf/bpf.go
- pkg/bpf/bpf_restart.go
- pkg/bpf/bpf_restart_test.go
/kind cleanup
Fixes #
**Special notes for you're reviewer**:
```release-note
```
> some cleanups and rename on start type

- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
/kind bug
Fixes #815
```release-note
```
> fix crash when waypoint is not network address type

- Makefile
- hack/utils.sh
Now run make docker VERSION=x.y.z can be passed to builder container, and  kmesh-daemon version can show x.y.z
Fixes #
```release-note
```
> Support passing VERSION to docker when run make docker

- pkg/bpf/bpf.go
- pkg/bpf/bpf_restart_test.go
- pkg/controller/ads/ads_processor_test.go
- pkg/status/status_server.go
- pkg/status/status_server_test.go
- pkg/utils/test/bpf_map.go
/kind bug
Because cleanup bpf map in `loader.Stop()`. so there is no need to execute `bpf.cleanup` again
Fixes #844 
```release-note
```
> fix clean bpf_map twice in test

- pkg/controller/workload/bpfcache/auth_policy.go
- pkg/controller/workload/bpfcache/backend.go
- pkg/controller/workload/bpfcache/common.go
- pkg/controller/workload/bpfcache/endpoint.go
- pkg/controller/workload/bpfcache/fake_map.go
- pkg/controller/workload/bpfcache/frontend.go
- pkg/controller/workload/bpfcache/service.go
- pkg/controller/workload/workload_controller.go
- pkg/controller/workload/workload_controller_test.go
- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
- pkg/status/status_server.go
- pkg/status/status_server_test.go
feature
Fixes #
```release-note
```
> support dump workload bpf map

- pkg/controller/telemetry/accesslog.go
- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/metric_test.go
/kind bug
Fixes #811 
```release-note
```
> Fix accesslog

- daemon/main.go
- daemon/manager/manager.go
- pkg/auth/rbac.go
- pkg/bpf/bpf.go
- pkg/cache/v2/listener.go
- pkg/cache/v2/maps/listener.go
- pkg/cni/install.go
- pkg/cni/plugin/plugin.go
- pkg/controller/ads/ads_controller.go
- pkg/controller/bypass/bypass_controller.go
- pkg/controller/config/config.go
- pkg/controller/controller.go
- pkg/controller/manage/manage_controller.go
- pkg/controller/security/manager.go
- pkg/controller/telemetry/utils.go
- pkg/controller/workload/bpfcache/factory.go
- pkg/controller/workload/workload_controller.go
- pkg/dns/dns.go
- pkg/logger/logger.go
- pkg/status/status_server.go
- pkg/utils/exec.go
> make default logger only print to stderr not file

- pkg/cni/install.go
- pkg/cni/kubeconfig.go
```
time="2024-09-19T03:22:34Z" level=info msg="got event CHMOD         \"/var/run/secrets/kubernetes.io/serviceaccount/..2024_09_19_03_22_34.2403565555\"" subsys="cni installer"
time="2024-09-19T03:39:30Z" level=info msg="grpc reconnect succeed" subsys=controller
time="2024-09-19T04:11:58Z" level=info msg="got event CREATE        \"/var/run/secrets/kubernetes.io/serviceaccount/..2024_09_19_04_11_58.3748894910\"" subsys="cni installer"
time="2024-09-19T04:11:58Z" level=info msg="kubeconfig either does not exist or is out of date, writing a new one" subsys="cni installer"
time="2024-09-19T04:11:58Z" level=info msg="wrote kubeconfig file /etc/cni/net.d/kmesh-cni-kubeconfig" subsys="cni installer" …
```
> remove spammy cni installer log

- daemon/manager/manager.go
Now kmesh-daemon has unwanted subcommand `completion`:
```bash
[root@kmesh-7jz9n kmesh]# kmesh-daemon --help
Start kmesh daemon
Usage:
kmesh-daemon [flags]
kmesh-daemon [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
dump        Dump config of ads or workload mode
help        Help about any command
log         Get or set kmesh-daemon's logger level
uninstall   Uninstall kmesh-cni
version     Print the version of kmesh daemon
```
And will ignore invalid flag:
```
[root@kmesh-7jz9n kmesh]# kmesh-daemon --abc
time="2024-09-23T02:46:14Z" level=info msg="FLAG: --bpf-fs-path=\"/sys/fs/bpf\"" subsys=manager
time="2024-09-23T02:46:14Z" level=info msg="FLAG: …
```
> optimize kmesh-daemon binary

- bpf/include/bpf_common.h
- bpf/include/inner_map_defs.h
- bpf/kmesh/ads/include/kmesh_common.h
- bpf/kmesh/ads/include/tail_call_index.h
- bpf/kmesh/bpf2go/bpf2go.go
- config/kmesh_marcos_def.h
- kmesh_macros_env.sh
- pkg/bpf/bpf_kmesh_common.go
- pkg/bpf/bpf_kmesh_workload.go
- pkg/utils/kernel_version.go
**Problem:** Kernel version lower than 5.13 does not support `bpf_snprintf()`, thus eBPF log can not be redirected to Kmesh daemon. There is no good solution for now.
**Solution:** Build 2 series of eBPF objects, one of them with `-DKERNEL_VERSION_HIGHER_5_13_0=0`, another with `-DKERNEL_VERSION_HIGHER_5_13_0=1`. When Kmesh starts up, detect the kernel version then load one of them.
Fixes #
```release-note
NONE
```
TODOs:
1. Use `interface` to reduce code lines
> Build 2 series of eBPF objects(kernel ver. <5.13 & >=5.13) and load eBPF dynamically when Kmesh starts up

- pkg/controller/ads/ads_controller.go
- pkg/controller/ads/ads_controller_test.go
- pkg/controller/client.go
- pkg/controller/workload/workload_controller.go
/kind bug
When quickly launching a large number of pods and services in a Kubernetes cluster, the kmesh handadsresponse speed is insufficient. Additionally, the gRPC stream's sending and receiving code runs in the same coroutine, which can lead to deadlock issues. We are now separating the sending and receiving processes of the gRPC stream into different coroutines.
Fixes #
```release-note
```
> make xds request send async

- bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
- bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.h
- pkg/bpf/bpf_kmesh.go
- pkg/bpf/bpf_kmesh_l4.go
- pkg/cache/v2/cluster.go
- pkg/cache/v2/cluster_test.go
- pkg/cache/v2/listener.go
- pkg/cache/v2/listener_test.go
- pkg/cache/v2/maps/authz.go
- pkg/cache/v2/maps/cluster.go
- pkg/cache/v2/maps/listener.go
- pkg/cache/v2/maps/route.go
- pkg/cache/v2/route.go
- pkg/cache/v2/route_test.go
- pkg/status/status_server.go
- pkg/status/status_server_test.go
feature
support cluster lookup all for dump all the kv of bpf map.
It's for #820 
i've met some problem in developing, seems to be related to the deserialization problem(#702 ) talked about before:
i update cluster 1 here, but the lookup and the newly written lookupall both got empty cluster name.
the output is:
lookup: cluster: api_status:UPDATE  connect_timeout:1, api_status:UPDATE  name:"ut-cluster-2"  connect_timeout:1
`ut-cluster-2` is shown, but `ut-cluster-1` does not work.
If we only define `Name` field, the test will even panic.
Fixes #
```release-note
```
> Support ads bpf map lookup all

- pkg/bpf/bpf_kmesh.go
Enhanced kernel: Build 2 series of eBPF objects(kernel ver. <5.13 & >=5.13) and load eBPF dynamically when Kmesh starts up
Fixes #
```release-note
NONE
```
> Enhanced kernel: Build 2 series of eBPF objects(kernel ver. <5.13 & >=5.13) and load eBPF dynamically when Kmesh starts up

- pkg/controller/manage/manage_controller.go
- pkg/utils/enroll.go
- pkg/utils/enroll_test.go
/kind cleanup
Fix argument list too long in manage controller in https://github.com/kmesh-net/kmesh/pull/679
Fixes #
```release-note
NONE
```
> Fix argument list too long in manage controller

- ctl/dump/dump.go
- daemon/options/bpf.go
- deploy/charts/kmesh-helm/values.yaml
- deploy/yaml/kmesh.yaml
- pkg/auth/policy_store_test.go
- pkg/auth/rbac_test.go
- pkg/bpf/bpf.go
- pkg/bpf/bpf_test.go
- pkg/cache/v2/cluster_test.go
- pkg/cache/v2/listener_test.go
- pkg/cache/v2/route_test.go
- pkg/cni/chained_test.go
- pkg/cni/install.go
- pkg/cni/install_test.go
- pkg/cni/plugin/plugin.go
- pkg/constants/constants.go
- pkg/controller/ads/ads_processor.go
- pkg/controller/ads/ads_processor_test.go
- pkg/controller/client.go
- pkg/controller/client_test.go
- pkg/controller/config/config.go
- pkg/controller/controller.go
- pkg/controller/manage/manage_controller.go
- pkg/controller/manage/manage_controller_test.go
- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
- pkg/logger/logger.go
- pkg/status/status_server_test.go
Fixes #937 
```release-note
```
> change `ads`->`kernel-native` and `workload`->`duel-engine` in code

- ctl/waypoint/waypoint.go
/kind bug
Before this fix:
```bash
root@dev:~/kmesh# kmeshctl waypoint status --help
Show the status of waypoints for the namespace provided or default namespace if none is provided
Usage:
kmeshctl waypoint status [flags]
Examples:
kmeshctl waypoint status
kmeshctl waypoint status --namespace default
Flags:
-h, --help   help for status
```
After this fix:
```bash
root@dev:~/kmesh# ./kmeshctl waypoint status --help
Show the status of waypoints for the namespace provided or default namespace if none is provided
Usage:
kmeshctl waypoint status [flags]
Examples:
kmeshctl waypoint status
kmeshctl waypoint status --namespace default
Flags:
```
Fixes # …
> fix format error of `kmeshctl waypoint status --help`

- .github/workflows/release-master.yaml
- build/docker/github.dockerfile
: without this, though the docker image is ar,64 arch but  the kmesh-daemon within it is just x86-64.
Fixes https://github.com/kmesh-net/kmesh/issues/944
```release-note
```
> Fix github action arm image built

- pkg/controller/manage/manage_controller.go
- pkg/controller/manage/manage_controller_test.go
- pkg/utils/enroll.go
/kind bug
Fixes #956
```release-note
```
> check whether pods should be managed when ns is managed

- test/e2e/baseline_test.go
- test/e2e/run_test.sh
> E2E Enhancement Draft

- bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
- bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.h
Since map_fd cannot be used universally in different processes, 
map_fd needs to be converted into map_id and stored, and then 
converted into map_fd in the corresponding process when the 
configuration is restored.
Fixes #
```release-note
```
> g_inner_map_mng.inner_map support persist in restart

- bpf/kmesh/workload/include/service.h
- bpf/kmesh/workload/include/workload.h
- bpf/kmesh/workload/include/workload_common.h
- pkg/controller/workload/bpfcache/endpoint.go
- pkg/controller/workload/bpfcache/locality_cache.go
- pkg/controller/workload/bpfcache/locality_cache_test.go
- pkg/controller/workload/bpfcache/service.go
- pkg/controller/workload/cache/endpoint_cache.go
- pkg/controller/workload/cache/endpoint_cache_test.go
- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
- pkg/status/status_server_test.go
~This PR is not ready to be merged; some features are not working properly.~
~1. The priority of the service Pod written to the BPF map is observed to be correct in user space, but the behavior of locality load balancing in kernel space is random. (This issue does not exist in the test version of the code at [this link](https://github.com/derekwin/kmesh/tree/lb-dev-user-bak).)~
~2. The code for the workload has undergone significant changes in the past one to two months. The current PR's code attempts to adapt to the new logic of the workload as much as possible. However, a lot of redundant deletion behaviors have been observed. These parts of the code need to be optimized in conjunction with the existing workload logic.~
This pr is ok.
But i …
> Add locality loadbalance to kmesh workload mode.

- pkg/controller/ads/ads_controller.go
- pkg/controller/ads/ads_processor.go
- pkg/controller/ads/ads_processor_test.go
/kind bug
fix cannot get RDS after grpc reconnect
after grpc reconnect,we did not clear the cache, and we forget to compare lastNonce in RDS,  so the judgment logic in the subsequent process believes that RDS does not need to be updated. 
Fixes #964 
```release-note
```
> fix cannot get RDS after grpc reconnect

- bpf/include/bpf_log.h
- bpf/include/common.h
- daemon/manager/manager.go
- pkg/bpf/ads/loader.go
- pkg/bpf/ads/loader_enhanced.go
- pkg/bpf/bpf.go
- pkg/bpf/workload/loader.go
- pkg/status/status_server.go
- pkg/status/status_server_test.go
A part of  #977 
```release-note
```
> A constant map is used to pass constants

- pkg/controller/workload/cache/service_cache.go
- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
Starting from istio 1.24, waypoint supports the address type of hostname and Kmesh need to support it.
Fixes part of #984
```release-note
```
> handle hostname type waypoint for istio 1.24

- bpf/kmesh/ads/include/circuit_breaker.h
- bpf/kmesh/ads/include/ctx/sock_ops.h
cleanup
ads L4 mode please check https://github.com/kmesh-net/kmesh/issues/998
Fixes #
```release-note
```
> Some fix about circuit breaker

- Makefile
- ctl/accesslog/accesslog.go
- ctl/utils/utils.go
- ctl/waypoint/waypoint.go
- go.mod
- pkg/kube/client.go
- pkg/kube/portforwarder.go
This PR reduces the binary size of `kmeshctl` by replacing the dependency on `istio.io/istio/pkg/kube` and applying build flags to strip debugging symbols. 
Closes #946
I noticed that `test/e2e/main_test.go` uses `istio.io/istio/pkg/kube`. Do I need to do anything about it?
```release-note
```
> feat: reduce binary size of kmeshctl

- pkg/controller/workload/workload_processor.go
- test/e2e/baseline_test.go
Fixes #1037
```release-note
```
> add e2e test for service entry with inlined workload entry

- bpf/include/bpf_log.h
- bpf/include/common.h
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfel.go
- bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfeb.go
- bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfel.go
- bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfeb.go
- bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfel.go
- bpf/kmesh/workload/sockops.c
- deploy/yaml/clusterrole.yaml
- pkg/bpf/bpf.go
- pkg/bpf/bpf_test.go
- pkg/constants/constants.go
- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/metric_test.go
- pkg/status/status_server.go
Fixes #961 
```release-note
```
> Use bpf map to pass node IP and pod sub gateway. Skip kubelet probe traffic management from ebpf

- .github/workflows/main-5.15.yml
- bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
- hack/run-ut.sh
- hack/utils.sh
This to make sure bpf prog can be loaded successfully in kernel 5.15,  since github action has a limited node image. So uubuntu 2004 is the smallest version that we can use.
We have encountered many cases that previous CI can run successfully, but in our local dev machine(kernel 5.15) it failed.
See https://github.com/kmesh-net/kmesh/issues/1053
Fixes #
```release-note
```
> Add kmesh ut test on 5.15

- bpf/kmesh/workload/include/backend.h
- bpf/kmesh/workload/include/service.h
/kind bug
Fixes #
```release-note
```
> optimize: fix bpf ins over 100w

- test/e2e/baseline_test.go
/kind bug
This test case, after the waypoint is deployed, incorrectly checks whether it's L4 traffic instead of L7. When test runs fast enough, before the waypoint is deployed, the test has been completed, the test will pass. However, if the waypoint is deployed successfully during the test, it will fail, which is why this case is often flakey.
Fixes #967
```release-note
```
> fix Flake of TestAddRemovePodWaypoint

- pkg/controller/workload/bpfcache/endpoint.go
- pkg/controller/workload/bpfcache/endpoint_test.go
- pkg/controller/workload/cache/endpoint_cache.go
- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
No matter workload/service update, we should make sure bpf map is updated in the following orders:
backendmap-> endpoint map -> service map -> frontend map
In case workload/service delete, the order should be as below:
frontend map-> service map -> endpoint map -> backend map
Fixes #1042
And made many cleanups
```release-note
```
> Correct Workload handle order

- samples/addons/prometheus_recording_istio.yaml
This PR supplies a new Prometheus configuration file in Kmesh samples. Compared with the origin one in `samples/addons/prometheus.yaml`, this new Prometheus configuration file adds some modifications to help Kiali drawing Traffic Graph based on metrics generated by Kmesh.
- Add some recording rules which rename the Kmesh service tcp metrics to Istio standard tcp metrics. This makes Kiali recognize these tcp metrics and draw tcp-based Traffic Graph.
- Besides, a metrics relabel config is added to the scrap_configs, in order to rename the `reporter=waypoint` label to `reporter=destination`. Through this relabel config, Kiali can read http metrics exposed by waypoint without having to recognize that the …
> add configuration to collect the Prometheus metrics from Kmesh and rename them into a format that Kiali can read.

- samples/addons/kiali.yaml
- samples/addons/prometheus_recording_istio.yaml
Add kiali addon sample and  adjust prometheus_recording_istio sample for a better view of kiali
Fixes #1100
This PR mainly fixes of the already existed `./samples/addon/prometheus_recoding_istio.yaml` and further provide a `kiali.yaml` for a sample Kiali deploy.
We can get a pretty decent sample traffic graph in Kiali with this and #1094 both resolved. The final look of the traffic graph will be like this
> Add kiali addon sample and  adjust prometheus_recording_istio sample

- pkg/bpf/bpf.go
/kind bug
Not all clustered environments have `podCIDR`.
Therefore optimised for handling in this case
Fixes #
```release-note
```
> Optimised handling when no podCIDR is available

- bpf/kmesh/probes/tcp_probe.h
Extend the ringbuf size of tcp_info to avoid ringbuf reserve failure during high concurrency.
tcp_info reports 96bytes of data at a time. Combined with real usage, I think having 2000 simultaneous accesses to a link on a node is going to cover most usage scenarios. 
So choose to set the size of ringbuf to 256KB.
Fixes #
```release-note
```
> Expand the ringbuf size of tcp_info

- Makefile
- ctl/version/version.go
- daemon/manager/manager.go
- daemon/manager/version/version.go
- docs/ctl/kmeshctl_version.md
- pkg/kube/portforwarder.go
Fixes https://github.com/kmesh-net/kmesh/issues/1112
Fix https://github.com/kmesh-net/kmesh/issues/1110
The output now 
```
$ kmeshctl version
client version: 1.0-dev-ce162fb7634b6122966da01fd45147e319b7625e
kmesh-daemon version: 1.0-dev-ab83d8ccffaca860a5a657d7873afddd5327a122 (2 daemons)
```
```release-note
```
> Add kmesh-daemon version subcommand and fix `kmeshctl version`

- pkg/controller/ads/cache.go
- pkg/controller/telemetry/accesslog.go
- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/metric_test.go
- pkg/controller/workload/cache/waypoint_cache.go
- pkg/controller/workload/cache/waypoint_cache_test.go
- pkg/controller/workload/workload_controller.go
- pkg/controller/workload/workload_processor.go
- test/e2e/baseline_test.go
/kind bug
Fixes #1089. Update `destination_service_name` to service name instead of host.
Here are some issues tha remain to be disccused:
- When a service is not found when building service metrics, I record the `dstIp` in `destination_service`, I'm not sure if it is appropriate.
- When recording waypoint metrics, services can not found since the `dstIp` is 15019, but only 15021 and 15008 are defined in waypoint services, so the following logic fails every time. Ztunnel uses actual service as destination service instead of the waypoint service, but seems like kmesh can not achieve that. I'm not sure how to handle this situation.
```go
namespacedhost := ""
if dstWorkload != nil {
for k, …
```
> update hostname and record unknown services of service metrics

- test/e2e/baseline_test.go
Test that ServiceEntry and WorkloadEntry are different resource objects and SE selects WE through selector.
Fixes #
```release-note
```
> add E2E test "TestServiceEntrySelectsWorkloadEntry"

- pkg/controller/manage/manage_controller.go
/kind cleanup
This is motivated by @bitcoffeeiux refereencing this controller. I found there are something not perfect here.
1.  We donot need shared informer factory here. 
2.  The controller Run() method cannot be stopped
3. We can reuse the handlePodUpdate function to process add event
Others are mostly clean code
Fixes #
```release-note
```
> misc bug fix in manage controller

- bpf/include/errno.h
- bpf/kmesh/probes/tcp_probe.h
- bpf/kmesh/workload/cgroup_sock.c
- bpf/kmesh/workload/include/backend.h
- bpf/kmesh/workload/include/frontend.h
- bpf/kmesh/workload/sendmsg.c
- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/metric_test.go
- pkg/controller/workload/cache/service_cache.go
Currently kmesh get destination service info by looking up from the services of a workload, which may not properly handle circumstances below:
1. multiple services with same workload backend, for example, `example-a.com` and `example-b.com` share the same workload backend, and the ports of them are exactly the same, currently kmesh can only guess the destination service since currently only workload info is passed to the metric controller.
2. for requests redirected to the waypoint, the metrics will be like:
```shell
kmesh_tcp_connections_closed_total{destination_app="reviews-svc-waypoint",destination_service_name="reviews-svc-waypoint"...} 14
```
both `destination_app` and `destination_service` will be the waypoint, and …
> refine destination service metrics generation

- bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
- pkg/bpf/ads/sock_connection.go
- pkg/cache/v2/listener_test.go
- pkg/utils/test/bpf_map.go
/kind bug
When applying and deleting the same yaml configuration repeatedly, services or pods will be continuously created and deleted. At this time, the number of records in the ebpf-map will not be completely deleted, causing the memory usage of ebpf_map to continue to grow.
Fixes #
```release-note
```
> fix ebpf map elem nums grow abnormal

- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
Fixes  https://github.com/kmesh-net/kmesh/issues/1162
Currently istiod does not support pushing only local authorizations. 
```release-note
```
> Filter unused authz

- bpf/kmesh/workload/include/authz.h
Fixes #1157 
```release-note
```
> improve xdp bpf log

- .github/workflows/release.yml
Ability to automatically push helm packages at publicize release.
Add `make helm-push` comment in workload.
Fixes #
```release-note
```
> Ability to automatically push helm packages at publicize release

- pkg/controller/security/manager_test.go
/kind bug
Fixes #1167 
```release-note
```
> fix DATA RACE in TestCertRoute

- pkg/bpf/bpf.go
- pkg/constants/constants.go
/kind bug
kmesh currently does not support Update mode. When starting from Update mode, it should start in Normal mode. However, all residual data is not properly cleared, resulting in a startup error.
Fixes #
```release-note
```
> fix Update mode failed

- bpf/kmesh/probes/tcp_probe.h
- pkg/controller/telemetry/accesslog.go
- pkg/controller/telemetry/accesslog_test.go
- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/utils.go
Added dimensions of Kmesh workload granularity for metrics and accesslog.
Metrics add :
```
tcpConnectionTotalRetransInWorkload = prometheus.NewGaugeVec(
prometheus.GaugeOpts{
Name: "kmesh_tcp_workload_connections_total_retrans",
Help: "The total number of TCP connections retried to a workload.",
}, workloadLabels)
tcpConnectionLostOutInWorkload = prometheus.NewGaugeVec(
prometheus.GaugeOpts{
Name: "kmesh_tcp_workload_connections_lost_out",
Help: "The total number of packets lost by the workload over TCP connections.",
}, workloadLabels)
```
accesslog add:
```
srtt=%dus, min_rtt=%dus,
```
Fixes #1091 
**Does this PR introduce a …
> add workload metrics

- ctl/authz/authz.go
- Added confirmation messages in the 'enable' and 'disable' commands to inform users
when authorization offloading is successfully enabled or disabled.
- Introduced a new 'status' subcommand that queries and displays the current authorization
status from the Kmesh daemon pod(s).
- Refactored authz command handling to support both single and multiple pod scenarios.
- These improvements enhance the overall user experience and provide better debugging
and verification of authz state.
Fixes #1181
> Improve Authz UX: Immediate Feedback & Status Subcommand

- bpf/kmesh/ads/include/route_config.h
Due to the excessive number of instructions consumed by BPF_LOG, using BPF_LOG within the loop can easily lead to exceeding 1,000,000 instructions. A small optimization is needed to avoid surpassing this limit.
Fixes #
```release-note
```
> adapt BPF_LOG in route_config.h

- bpf/kmesh/workload/include/authz.h
- bpf/kmesh/workload/xdp.c
Fixes #1207 
```
Previously, since the xdp program only supports ip and port, policies configured with ns and principal types need to be
switched to user mode. However, the logic for determining whether to switch to user mode was wrong. The previous logic
was that when policy_index is greater than `MAX_MEMBER_NUM_PER_POLICY`, it will determine whether to switch to
user mode. However, `MAX_MEMBER_NUM_PER_POLICY` is a fixed value, and the number of deployed policies may be
less than this number.
The correct logic should be to traverse all policies in xdp. In each policy, if the policy does not match, the result of authz
will be stored in `match_ctx->auth_result`. If all policies are …
```
> optimizie xdp auth

- pkg/bpf/bpf.go
Previously, the auth offload function only supported port, so this function was disabled by default. Now auth offload supports ip+port, and the rest of the auth policies can also be transferred to user mode for execution, so this function is enabled by default.
Fixes #
```release-note
```
> enable auth offload by default

- docs/proposal/tcp_long_connection_metrics.md
Proposal for "Metrics for TCP Long Connection"
LFX 2025 term-1
/kind feature
Fixes #1211 
```release-note
```
> Proposal for tcp_long_connection_metrics

- pkg/controller/workload/workload_controller.go
- pkg/controller/workload/workload_controller_test.go
- pkg/controller/workload/workload_processor.go
Fixes #1265 
When Kmesh is restarted, one thing to ensure is that the workload's xds configuration has been delivered before executing Rbac, otherwise, Rbac will reject the app request.
```release-note
```
> add channel for Rbac when Kmesh restart

- .github/workflows/e2e-ipv6-istio-1.25.yml
- .github/workflows/e2e-istio-1.25.yml
Fixes #1292
```release-note
```
> add e2e tests for isito 1.25 and remove e2e tests for isito 1.22

- bpf/include/bpf_helper_defs_ext.h
- bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockops_bpfeb.go
- bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockops_bpfel.go
- bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockopscompat_bpfeb.go
- bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockopscompat_bpfel.go
- kmesh_bpf_env.sh
- pkg/bpf/ads/loader.go
- pkg/bpf/ads/loader_enhanced.go
/kind bug
1.The helper function changes without timely adjusting the script, resulting in the helper function serial number error
2.The order of LoadKmeshCgroupSockCompat and LoadKmeshCgroupSock is reversed, causing compilation problems
3.GetBpfConfigVariable function is missing in enhanced mode
Fixes #
```release-note
```
> fix enhanced issue

- bpf/kmesh/bpf2go/dualengine/kmeshcgroupskb_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupskb_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupskbcompat_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupskbcompat_bpfel.go
- bpf/kmesh/probes/tcp_probe.h
- bpf/kmesh/workload/cgroup_skb.c
- bpf/kmesh/workload/sockops.c
/kind bug
added config.h include in tcp_probe.h and cgroup_skb.h 
Fixes #1334
```NONE
```
> rfac: added config.h include in tcp_probe.h and cgroup_skb.h

- bpf/include/bpf_common.h
- bpf/kmesh/probes/probe.h
- bpf/kmesh/workload/cgroup_skb.c
/kind bug
Fixes #1348
```release-note
```
> Fix cgroup_skb/* get sk_storage failed

- bpf/kmesh/bpf2go/dualengine/kmeshcgroupskb_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupskb_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupskbcompat_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupskbcompat_bpfel.go
- bpf/kmesh/workload/cgroup_skb.c
- pkg/bpf/bpf.go
- pkg/status/status_server.go
/kind feature
added periodic report knob for long connection
Fixes #1356 
```
added periodic report knob for long connection
```
> added periodic report knob for long connection

- hack/run-ebpf-ut.sh
- test/bpf_ut/Makefile
- test/bpf_ut/bpftest/bpf_test.go
- test/bpf_ut/bpftest/workload_test.go
- test/bpf_ut/workload_sockops.c
- test/bpf_ut/workload_sockops_test.c
```shell
> make ebpf_unit_test V=1 -j
... build
go test ./bpftest -bpf-ut-path /root/github/kmesh/test/bpf_ut -test.v
=== RUN   TestBPF
=== RUN   TestBPF/Workload
... XDP ut
=== RUN   TestBPF/Workload/SockOps
=== RUN   TestBPF/Workload/SockOps/workload_sockops_test.o
=== RUN   TestBPF/Workload/SockOps/workload_sockops_test.o/BPF_SOCK_OPS_TCP_CONNECT_CB
workload_test.go:357: km_manage[192.168.0.86] = 0
=== RUN   TestBPF/Workload/SockOps/workload_sockops_test.o/BPF_SOCK_OPS_ACTIVE_ESTABLISHED_CB__enable_encoding_metadata
workload_test.go:440: Connect success: 192.168.0.86:12345 -> 192.168.0.86:54321
workload_test.go:465: km_socket get key[192.168.0.86:12345->192.168.0.86:54321], test success.
=== RUN …
```
> eBPF unit test: add workload sockops ut

- bpf/kmesh/general/tc_mark_encrypt.c
- test/bpf_ut/Makefile
- test/bpf_ut/bpftest/bpf_test.go
- test/bpf_ut/bpftest/general_test.go
- test/bpf_ut/include/tc_common.h
- test/bpf_ut/tc_mark_decrypt_test.c
- test/bpf_ut/tc_mark_encrypt_test.c
```shell
> make ebpf_unit_test V=1 -j
... build
go test ./bpftest -bpf-ut-path /root/github/kmesh/test/bpf_ut -test.v
go test ./bpftest -bpf-ut-path /root/github/kmesh/test/bpf_ut -test.v
=== RUN   TestBPF
=== RUN   TestBPF/Workload
=== RUN   TestBPF/Workload/XDP
=== RUN   TestBPF/Workload/XDP/xdp_shutdown_in_userspace_test.o
=== RUN   TestBPF/Workload/XDP/xdp_shutdown_in_userspace_test.o/1_shutdown_in_userspace__should_shutdown
bpf_test.go:113: Running test /root/github/kmesh/test/bpf_ut/xdp_shutdown_in_userspace_test.o
bpf_test.go:264: Successfully registered tail call policies_check -> km_xdp_tailcall[0]
bpf_test.go:264: Successfully registered tail call policy_check -> km_xdp_tailcall[1] …
```
> eBPF unit test: add general tc ut

- bpf/kmesh/ads/include/cluster.h
- bpf/kmesh/workload/xdp.c
bpf_trace_printk cannot print two %s, need to fix
/kind bug
bpf_trace_printk cannot print two %s, need to fix
Fixes #
```release-note
```
> fix log cannot print in kernel 5.10 by bpf_trace_printk

- docs/proposal/tcp_long_connection_metrics.md
- pkg/controller/telemetry/accesslog.go
- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/metric_test.go
- pkg/controller/telemetry/utils.go
=/kind enhancement
outputAccesslog func to skip accesslog at conn establishment
Fixes #1375
```release-note
```
> rfac: outputAccesslog func to skip accesslog at conn establishment

- bpf/kmesh/probes/probe.h
- bpf/kmesh/probes/tcp_probe.h
- pkg/controller/manage/manage_controller.go
For https://github.com/kmesh-net/kmesh/issues/1381
eliminate these logs during pod shutdown
```
time="2025-05-09T01:32:09Z" level=info msg="default/ws-server: enable Kmesh manage" subsys=manage_controller
time="2025-05-09T01:32:09Z" level=info msg="add annotation for pod default/ws-server" subsys=manage_controller
time="2025-05-09T01:32:09Z" level=info msg="default/ws-client: enable Kmesh manage" subsys=manage_controller
time="2025-05-09T01:32:09Z" level=info msg="add annotation for pod default/ws-client" subsys=manage_controller
```
```
// this is because the connection is established before kmesh starts
time="2025-05-09T01:32:39Z" level=info msg="[PROBE] ERR: on close: bpf_sk_storage_get failed\n" subsys=ebpf
``` …
> Fix: unexpected log when pod is shutting down

- ctl/version/version.go
- ctl/version/version_test.go
/kind bug
Fixes #1364 
```release-note
```
> fix kmeshctl version report error

- bpf/kmesh/workload/include/frontend.h
- bpf/kmesh/workload/xdp.c
- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
…rontend map for xdp use
Fixes #1381
```release-note
```
> Fix authz during shutdown

- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/metric_test.go
/kind bug
refactored updateConnectionMetricCache to report connection-metrics correctly
Fixes #1370
```
correct long_conn metrics 
```
> refactored updateConnectionMetricCache to report connection-metrics correctly

- .gitignore
- config/.gitignore
- hack/format.sh
- kmesh_compile_env_pre.sh
`make format` will create a `markdownlint-cli2` container with random name every time, which needs to be fix.
Fixes #
```release-note
NONE
```
> Fix: make format with too many containers

- pkg/controller/encryption/ipsec/ipsec_controller.go
- pkg/controller/encryption/ipsec/ipsec_controller_test.go
/kind security
Add ipsec controller unit test. 
*Main content introduction as follows:*
1. TestNewIPsecController: Tests IPsec controller initialization including:
- Successful instance creation with proper environment setup
- Failure scenarios when required environment variables are missing
2. TestHandleKNIEvents: Validates KmeshNodeInfo event handling logic including:
-  handleKNIAdd: Tests adding remote nodes to workqueue while ignoring local nodes
- handleKNIUpdate: Verifies no queue addition for unchanged specs and SPI field updates triggering queue addition
3. TestMapOperations: Tests BPF map operations including:
- CIDR address add/delete operations
4. TestNodeOperations: Validates node …
> add ipsec controller unit test

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/question.md
- README.md
- docs/en/kmesh_support.md
Fixes a typo by replacing duel with dual in the following files:
* [README.md#L43](https://github.com/kmesh-net/kmesh/blob/73ea8402d1610ccbc77392827b0d66922cc52d22/README.md?plain=1#L43)
* [.github/ISSUE\_TEMPLATE/bug-report.md#L22](https://github.com/kmesh-net/kmesh/blob/73ea8402d1610ccbc77392827b0d66922cc52d22/.github/ISSUE_TEMPLATE/bug-report.md?plain=1#L22)
* [.github/ISSUE\_TEMPLATE/question.md#L20](https://github.com/kmesh-net/kmesh/blob/73ea8402d1610ccbc77392827b0d66922cc52d22/.github/ISSUE_TEMPLATE/question.md?plain=1#L20)
* [docs/en/kmesh\_support.md#L7](https://github.com/kmesh-net/kmesh/blob/73ea8402d1610ccbc77392827b0d66922cc52d22/docs/en/kmesh_support.md?plain=1#L7)
* …
> Fix typo : Duel to Dual

- ctl/secret/secret.go
- docs/ctl/kmeshctl.md
- docs/ctl/kmeshctl_secret.md
- docs/ctl/kmeshctl_secret_create.md
/kind feature
This PR simplifies IPsec secret creation by implementing automatic key generation for the kmeshctl CLI tool.
Create the IPsec secret by `kmeshctl secret create`.
```release-note
NONE
```
> feat(kmeshctl):automatic key generation for ipsec secrets

- bpf/kmesh/general/include/tc.h
- bpf/kmesh/general/tc_mark_decrypt.c
- pkg/constants/constants.go
- pkg/controller/encryption/ipsec/ipsec_handler.go
- test/bpf_ut/bpftest/general_test.go
- test/bpf_ut/tc_mark_decrypt_test.c
/kind bug
Refactored traffic decrypt marking logic.
Added OutputMark configuration in ipsec_handler.go
If the protocol is ESP, it directly enters the decryption phase to match the xfrm state and then re-enters ingress. If the packet is successfully decrypted, it will be marked as 0xd0. If the packet is not ESP protocol  and has not been decrypted(mark != 0xd0), its mark will be set to 0x0, ensuring it does not match any policy and avoiding the issue described previously.
Fixes #1481 
```release-note
```
> Resolving communication issue between pods after enabling IPsec

- pkg/bpf/factory/factory.go
- test/bpf_ut/Makefile
- test/bpf_ut/bpftest/bpf_test.go
- test/bpf_ut/bpftest/workload_test.go
- test/bpf_ut/workload_cgroup_skb_test.c
> feat: add cgroup_skb eBPF program

- .github/workflows/sync-kmeshctl-docs.yml
/kind feature
- This PR updates the Sync kmeshctl Docs to Website GitHub Actions workflow to improve the synchronization of documentation between the kmesh-net/kmesh and kmesh-net/website repositories.
- It ensures that the website/docs/kmeshctl directory is created if missing and populated with all files from kmesh/docs/ctl. Additionally, it enhances the workflow to detect and sync new changes (content modifications, added files, and deleted files) using rsync with checksum comparison, addressing previous issues where changes were not recognized.
- This is necessary to maintain consistent and up-to-date documentation across repositories.
- Workflow will create PR for any changes.
- …
> feature(workflow): added Kmeshctl doc syncing workflow
