- bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
- bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.h
- depends/include/5.10.0-60.18.0.50.oe2203/bpf_helper_defs_ext.h
- depends/include/6.1/bpf_helper_defs_ext.h
- docs/kmesh_development_guide.md
- kernel/ko_src/kmesh_extension/Makefile
- kmesh.spec
> license check

- test/testcases/kmesh/oe_test_service_function/oe_test_service_function.sh
testcase oe_test_service_function bugfix.
testcase failed due to file directory incorrect.
> testcase service bugfix

- README-zh.md
- README.md
- docs/kmesh_commands-zh.md
- docs/kmesh_demo-zh.md
- docs/kmesh_demo.md
docs: update english readme for kmesh cmds & fix some mistakes for demo presentation link
> docs: update english readme for kmesh cmds & fix some mistakes for demo presentation link

- README.md
add mailing, slack and twitter  link
> docs: add contact/contributing/lcs in readme

- README.md
A few headlines been updated from ### to ##.
Also added credit to thanks openEuler for the early day incubation and promotion help.
> Fix headlines and add credit

- docs/kmesh_kernel_compile-zh.md
- docs/kmesh_kernel_compile.md
> kernel compile doc

- bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
- bpf/kmesh/include/kmesh_common.h
- build.sh
- config/kmesh_marcos_def.h
- kmesh_compile_env_pre.sh
- kmesh_macros_env.sh
Optimize the build script to support one-click builds.
Add a new compile macro to adapt to lower versions of libbpf, improving code compatibility.
> optimize the build script

- build.sh
- kmesh_compile_env_pre.sh
- kmesh_macros_env.sh
- oncn-mda/include/mesh_accelerate.h
1、optimize the compilation process，remove unnecessary log printouts
2、fix compile error with low version libbpf
3、fix compile error in oncn-mda
> fix some compile error & optimize the compilation process

- README-zh.md
- README.md
> update kmesh image repo

- README-zh.md
- README.md
> add meeting notes link

- build.sh
- build/docker/start_kmesh.sh
- kmesh_macros_env.sh
1、support build in arm Ubuntu
2、optimize OE_23_03 macro
3、optimize image scripts
> Optimized build and image startup scripts

- Makefile
- build/docker/kmesh.dockerfile
- build/docker/kmesh.yaml
- build/docker/start_kmesh.sh
- kmesh.spec
add kmesh-cniplugin in build and rpmbuild scripts for kmesh images-l4 start
> support kmesh images-l4

- OWNERS
Promote code owners as per community membership
> Promote code owners as per community membership

- README-zh.md
- README.md
- build/docker/README.md
- build/docker/kmesh.yaml
- docs/kmesh_compile-zh.md
- docs/kmesh_compile.md
1、Added documentation for online compilation images, including usage, construction, and runtime process of the images. 
2、added some annotations to the yaml files.
> docs:image build and usage

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/good-first.md
- .github/ISSUE_TEMPLATE/question.md
> add issus template

- .github/PULL_REQUEST_TEMPLATE.md
add a pr template. Improve the underlying infrastructure of Kmesh to make it more convenient for other developers to submit pull requests.
> add a pr template

- build/docker/clusterrolebinding.yaml
- pkg/cni/chained.go
kind bug
Fixes https://github.com/kmesh-net/kmesh/issues/113
```release-note
Modify clusterrolebinding, add the lost namespace, and change the file name.
```
> fix kmesh start failed, cannot connect to istiod

- kmesh_compile.sh
Add one of the following kinds:
modify kmesh_compile.sh to suit different arch
Fixes #76 
NONE
```release-note
```
> modify kmesh_compile.sh to suit different arch

- go.mod
- pkg/cache/v2/cluster.go
- pkg/cache/v2/route.go
- pkg/controller/envoy/ads_event.go
- pkg/controller/envoy/ads_loader.go
> Follow up #103

- build/docker/kmesh.yaml
- pkg/controller/envoy/ads_config.go
/kind bug
fix simple config error
Fixes part of #75
```release-note
```
> fix misconfig of node.ID

- deploy/helm/templates/daemonset.yaml
bug
fix :helm install kmesh failed
Fixes #
```release-note
```
> fix:helm install kmesh failed

- deploy/helm/templates/daemonset.yaml
- deploy/helm/values.yaml
> Specifying Kmesh startup parameters during Helm installation

- deploy/helm/values.yaml
> Sync Image Tags Between Helm Chart and Registry

- Makefile
/kind bug
Fixes #128
```release-note
```
> Added default image hub target and tag

- deploy/helm/values.yaml
- deploy/yaml/kmesh.yaml
cleanup
Fixes #
```release-note
```
> The YAML adapted for version 0.2.0

- README-zh.md
- README.md
- build/docker/README.md
- deploy/README.md
- docs/kmesh_compile-zh.md
- docs/kmesh_compile.md
- docs/multiple dataplane_CN.md
- docs/multiple dataplane_EN.md
documentation
Adapting the release documentation for kmesh v0.2.0
Fixes #
```release-note
```
> Adapting the release documentation for kmesh v0.2.0

- .github/workflows/main.yml
Demonstrate UT coverage in CI. Allow developers to create pull request with a clear understanding of the UT coverage of their code.
**Which issue(s) this PR fixes**: 
a part of #104
> Demonstrate UT coverage in CI

- .github/workflows/main.yml
- go.mod
- go.sum
- pkg/cni/plugin/plugin.go
- pkg/cni/plugin/plugin_test.go
- pkg/logger/logger.go
> A ut of cni plugin

- pkg/cni/chained_test.go
> add ut of cni_chain

- .github/workflows/main.yml
Modify the go version in the github CI to match the version in go.mod
> Modify the go version in the github CI to match the version in go.mod

- .github/ISSUE_TEMPLATE/membership-request.md
Added an issue template for requesting to be a member of the kmesh community.
Helps developers who want to join the kmesh community to write issues more easily.
> Added an issue template for requesting to be a member of the kmesh community

- pkg/controller/envoy/ads_event.go
- pkg/controller/envoy/ads_loader.go
…s and cds are WildcardType
Fixes #https://github.com/kmesh-net/kmesh/issues/144
```release-note
```
> set resource name when response for rds and eds type

- pkg/controller/OWNERS
Added below guys as controller reviewers, who have contributed many of the prs. And are qualified  i think.
- @supercharge-xsy
- @YaoZengzeng
- @kwb0523
> Add reviwers for controller

- pkg/controller/envoy/ads_loader.go
/kind bug
add nil pointer check in ads_loader.go
Fixes #169
> add nil pointer check in ads_loader.go

- pkg/cni/chained.go
/kind bug
Fixes #150
```release-note
Fixed kmesh cni installer write empty cni conflist when kmesh daemon is restarted.
```
> Prevent writing empty cni conflist

- build/docker/start_kmesh.sh
/kind bug
Fixes #
```release-note
```
> fix start script

- pkg/nets/config.go
Move the map of supported protocols out of ParseConfig() for easy querying.
> Move the map of supported protocols out of ParseConfig() for easy querying.

- go.mod
- go.sum
- pkg/controller/envoy/ads_stream_test.go
> add ut of ads_stream.go

- go.mod
- go.sum
- pkg/controller/envoy/convert_filter_test.go
add ut of convert_filter_test.go
a part of #104
> add ut of convert_filter_test.go

- pkg/controller/envoy/ads_event.go
…erStatus
/kind bug
Fixes #185
> Change `UpdateApiClusterStatus` in handleLdsResponse to `UpdateApiListenerStatus`

- pkg/controller/workload/workload_event.go
> Fix workload remove

- build/docker/kmesh.dockerfile
- build/docker/start_kmesh.sh
- kmesh_compile.sh
improve portability of running images
Fixes #
```release-note
```
> Supports portability of running images

- pkg/controller/workload/workload_cache.go
- pkg/controller/workload/workload_event.go
- pkg/nets/nets.go
authorization and TLS encrypted transmission may need to get some info from workload data, so we should cache the workload data.
Fixes #
NONE
```release-note
```
> add workload cache to be retrieved

- pkg/cache/v2/cluster.go
- pkg/cache/v2/route.go
Fixed incorrect function usage when deleting routes
> Fixed incorrect function usage when deleting routes

- pkg/cache/v2/cluster_test.go
add ut of cache/v2/cluster.go
a part of #104
> add ut of cache/v2/cluster.go

- pkg/controller/envoy/ads_event_test.go
add ut of ads_event.go
a part of #104
> add ut of ads_event.go

- pkg/cache/v2/listener_test.go
add ut of cache/v2/listener.go
a part of #104
> add ut of cache/v2/listener.go

- pkg/cache/v2/route_test.go
add ut of cache/v2/route.go
a part of #104
> add ut of cache/v2/route.go

- pkg/cache/v2/cluster_test.go
Improved robustness of UT tests
> Improved robustness of UT tests

- pkg/cache/v2/listener_test.go
Improving the robustness of listener's ut
> Improving the robustness of listener ut

- pkg/controller/workload/workload_cache_test.go
add ut of workload_cache.go
a part of #104
> add ut of workload_cache.go

- pkg/controller/envoy/ads_event.go
- pkg/controller/envoy/ads_event_test.go
- pkg/controller/envoy/ads_stream.go
/kind bug
fix no responseNonce in AdsRequest
Fixes #201
> fix no responseNonce in AdsRequest

- go.mod
- go.sum
update golang.org/x/net to fix a vulnerability
Fix for [CVE-2023-45288](https://nvd.nist.gov/vuln/detail/CVE-2023-45288)
[information](https://pkg.go.dev/vuln/GO-2024-2687)
> update golang.org/x/net to fix a vulnerability

- pkg/bpf/bpf_kmesh_workload.go
/kind bug
Kmesh auth: fix npe
Fixes #
```release-note
NONE
```
> Kmesh auth: fix npe

- deploy/yaml/kmesh.yaml
there is a typo in deploy/yaml/kmesh.yaml, which results in failure to start kmesh with this yaml
Fixes #
```release-note
```
> Fix image name error in kmesh.yaml

- Makefile
- build/docker/README.md
- deploy/helm/templates/daemonset.yaml
- deploy/helm/values.yaml
- deploy/yaml/kmesh.yaml
- pkg/controller/config/config.go
- pkg/controller/config/config_test.go
> Fix POD_NAME env

- pkg/bpf/bpf_kmesh_common.go
- pkg/controller/envoy/ads_event_test.go
Added an demo for writing ut with bpf map operations
Fixes #
```release-note
```
> Added an example to test bpf map in ut

- bpf/kmesh/workload/include/workload.h
- pkg/controller/workload/workload_backend.go
- pkg/controller/workload/workload_event.go
- pkg/controller/workload/workload_frontend.go
> store waypoint data to bakcend map  and no service pod ip to forntend map

- bpf/kmesh/workload/sockops_tuple.c
- bpf/kmesh/workload/xdp.c
- pkg/bpf/bpf_kmesh_workload.go
- pkg/cni/plugin/plugin.go
/kind bug
fix prog name too long
Fixes #
```release-note
```
> Kmesh auth: fix prog name too long

- pkg/auth/rbac.go
- pkg/bpf/config.go
- pkg/controller/client.go
1. Kmesh auth: enable rbac only when Kmesh starts in workload mode
2. fix a typo
Fixes #
```release-note
NONE
```
> Kmesh auth: enable rbac only when Kmesh starts in workload mode

- pkg/controller/envoy/ads_event_test.go
- pkg/controller/envoy/ads_stream_test.go
Optimised UT with test bpf map in ut
a part of #104
> Optimised UT with test bpf map in ut

- pkg/auth/OWNERS
add OWNERS in pkg/auth
Fixes #
```release-note
NONE
```
> Kmesh auth: add OWNERS in pkg/auth

- daemon/manager/manager.go
- deploy/helm/values.yaml
- deploy/yaml/kmesh.yaml
- pkg/bpf/bpf.go
- pkg/bpf/config.go
- pkg/cni/config.go
- pkg/cni/install.go
- pkg/controller/client.go
- pkg/controller/config/config.go
- pkg/controller/controller.go
This is changing the --mode from ads to workload,  since we are in very early stage, i think it is ok.
> Enable workload mode by default

- Makefile
- docs/kmesh_compile-zh.md
- docs/kmesh_compile.md
- kmesh_compile.sh
> Revert "fix kmesh_compile image version"

- kmesh_compile.sh
Fix the issue of incorrect kmesh compile image version used in the kmesh_compile.sh script
Fixes #
```release-note
```
> fix kmesh_compile image version

- bpf/kmesh/workload/include/backend.h
- bpf/kmesh/workload/include/endpoint.h
- bpf/kmesh/workload/include/frontend.h
- bpf/kmesh/workload/include/service.h
Some log levels are not reasonable. Let's change them.
Fixes #
```release-note
```
> Kmesh: optimize log level

- build/docker/start_kmesh.sh
> Optimization: check and mount the bpf file system during kmesh startup

- bpf/kmesh/workload/cgroup_sock.c
- bpf/kmesh/workload/include/config.h
- bpf/kmesh/workload/include/workload.h
- bpf/kmesh/workload/sockops_tuple.c
- pkg/cni/plugin/plugin.go
- pkg/cni/plugin/plugin_test.go
Introduced a new method to mark pods managed by Kmesh via netcookie.
replace use classid. 
Fixes #
```release-note
```
> Kmesh: Introduce a new method record pod control by Kmesh

- pkg/cni/plugin/plugin.go
> Kmesh: Add the deleted annotation information to the pod

- README-zh.md
- README.md
- deploy/helm/templates/l7-envoyfilter.yaml
- deploy/yaml/l7-envoyfilter.yaml
/kind bug
Fixes #
```release-note
```
> fix cluster mismatch in envoyfilters and add arch suffix for waypoint image

- pkg/cni/plugin/plugin.go
> Kmesh: disable kmesh for waypoint pod

- pkg/controller/workload/workload_event.go
> store target port with KmeshWaypointPort for waypoint scene

- pkg/cni/plugin/plugin.go
> fix kmesh manager pod restart failed in ads mode

- deploy/helm/templates/daemonset.yaml
- deploy/yaml/kmesh.yaml
> Delete unnecessary code and configuration

- pkg/controller/envoy/ads_loader.go
- pkg/nets/nets.go
- pkg/nets/nets_test.go
Fixes #261
```release-note
```
> Fix dns typed service panic

- .github/dependabot.yml
> Enable dependa bot

- pkg/cache/v2/cluster_test.go
Added benchmark test for cluster.Flush()
> Added benchmark test for cluster.Flush()

- bpf/kmesh/workload/sockops_tuple.c
THis is a bug found by accessing hello world application from istio sample
> fix authz on server listening on both ipv4 and ipv6 port

- samples/httpbin/httpbin.yaml
- samples/sleep/sleep.yaml
add yaml of sample applications
> add yaml of sample applications

- deploy/helm/templates/daemonset.yaml
- deploy/yaml/kmesh.yaml
> remove duplicate NODE_NAME env

- pkg/controller/client.go
- pkg/controller/client_test.go
- pkg/controller/envoy/ads_event.go
- pkg/controller/envoy/ads_event_test.go
- pkg/controller/envoy/ads_stream.go
- pkg/controller/envoy/ads_stream_test.go
- pkg/controller/workload/workload_event.go
- pkg/controller/workload/workload_stream.go
/kind cleanup
Fix the error log. And do some cleanup
Fixes #282
```release-note
```
> Ignore expected grpc error

- bpf/kmesh/include/route_config.h
/kind bug
The problem was that using URI to match with domain led to the inability to find the correct route. The solution is to use host matching instead.
Fixes #244 
```release-note
```
> Fix the issue of incorrect domain matching

- docs/proposal/template.md
Added a proposal template, any future proposal can use this kind of template
> Add proposal template

- OWNERS
add reviewers and approvers in order to better manage the project
Examples of contributions：
xsy:
https://github.com/kmesh-net/kmesh/commits/main/?author=supercharge-xsy
bitcoffeeiux:
https://github.com/kmesh-net/kmesh/commits/main/?author=bitcoffeeiux
Fixes #
```release-note
```
> apply reviewers and approvers

- bpf/kmesh/cgroup_sock.c
- bpf/kmesh/workload/cgroup_sock.c
…e relevant process.
Fixes #
Currently supporting TCP protocol, add the corresponding checks
```release-note
```
> Currently supporting TCP protocol, add the corresponding checks 

- bpf/kmesh/cgroup_sock.c
- bpf/kmesh/workload/cgroup_sock.c
Fixes #
Currently supporting TCP protocol, add the corresponding checks
```release-note
```
> [release-0.3] Currently supporting TCP protocol, add the corresponding checks

- bpf/kmesh/include/route_config.h
/kind bug
Fixes #
```release-note
```
> [release-0.3]Fix the issue of incorrect domain matching

- pkg/auth/policy_store.go
Fixes #https://github.com/kmesh-net/kmesh/issues/332
```release-note
```
> only update by_key policy_store for workloadp scope authz

- .github/ISSUE_TEMPLATE/membership-request.md
- .github/ISSUE_TEMPLATE/question.md
documentation
Fix repo issue template typo errors
```release-note
```
> fix: fix issue template

- Makefile
- daemon/manager/manager.go
- daemon/manager/version/version.go
- pkg/version/version.go
feature
support kmesh daemon version command(#198)
Fixes #
```release-note
```
> feat: support kmesh daemon version command(#198)

- Makefile
add some clean job after make build, please check more info in the discussions in issue: https://github.com/kmesh-net/kmesh/issues/264
Fixes #264
```release-note
```
> fix: make clean does not clean up completely(#264)

- go.mod
- pkg/constants/constants.go
- pkg/controller/controller.go
- pkg/controller/security/caclient.go
- pkg/controller/security/manager.go
- pkg/controller/security/option.go
- pkg/controller/workload/workload_processor.go
- pkg/nets/connect.go
/kind feature
Fixes #
```release-note
```
> Certificate subscription management module to kmesh

- .github/workflows/main.yml
Monitoring code for UT coverage in github CI using codecov
Fixes #
```release-note
```
> Monitoring code for UT coverage in github CI using codecov

- pkg/controller/workload/workload_controller_test.go
- pkg/controller/xdstest/fake_xdsserver.go
add ut of workload_stream.go
a part of #104
> add ut of workload_stream.go

- Makefile
bug
Fix make clean errros.
Fixes #376
```release-note
```
> fix: make clean error(#376)

- deploy/README.md
documentation
optimize deploy/README.md
```release-note
```
> docs: optimize deploy/README.md

- CONTRIBUTING.md
- README.md
Added instructions on how to become a member of the Kmesh community to the readme.
Fixes #
```release-note
```
> Added instructions on how to become a member of the Kmesh community to the readme.

- build/docker/kmesh.dockerfile
- kmesh_compile.sh
/kind feature
when build with `make docker`, build is slow, especially in development of Kmesh.
Fixes #
```release-note
```
> optimization for kmesh build slow

- pkg/auth/rbac.go
- pkg/auth/rbac_test.go
- pkg/controller/client.go
- pkg/controller/security/manager.go
- pkg/controller/workload/cache/workload_cache.go
- pkg/controller/workload/cache/workload_cache_test.go
- pkg/controller/workload/workload_processor.go
This is adding check node name
> Improve isManagedWorkload

- pkg/status/status_server.go
feature
Support profiling in kmesh-daemon. Still WIP.
```release-note
```
> Support Profiling(#199)

- .github/workflows/release-master.yaml
> Add automatically docker image push

- bpf/kmesh/bpf2go/bpf2go.go
- bpf/kmesh/workload/sockops.c
- build.sh
- pkg/bpf/bpf_kmesh_workload.go
> Enable metadata encoder only for waypoint

- kmesh_compile.sh
> Fix build docker image in github action

- .github/workflows/release-master.yaml
- build/docker/kmesh.dockerfile
> Fix dockerimage binary size zero caused by permission

- pkg/auth/rbac.go
Fixes #https://github.com/kmesh-net/kmesh/issues/323
```release-note
```
> support identity rbac

- pkg/cache/v2/route.go
- pkg/controller/ads/ads_processor.go
- pkg/controller/client.go
- pkg/controller/client_test.go
- pkg/controller/controller.go
- pkg/controller/workload/cache/workload_cache.go
- pkg/status/status_server.go
Fixes part of https://github.com/kmesh-net/kmesh/issues/214
```release-note
```
> Dump workload

- pkg/controller/controller.go
- pkg/controller/security/caclient.go
- pkg/controller/security/manager.go
> Make use of FIFQ instead of priority queue

- Makefile
- hack/run-ut.sh
> add make test for run ut easily

- pkg/cni/plugin/plugin.go
- pkg/constants/constants.go
> Added dataplane mode constants

- pkg/controller/workload/workload_controller.go
- pkg/controller/workload/workload_processor.go
bug
Fixes #415
```release-note
```
> Subscribe cached resources when delta xds reconnect

- pkg/controller/ads/ads_controller_test.go
- pkg/controller/client_test.go
- pkg/controller/workload/bpfcache/fake_map.go
- pkg/controller/workload/workload_controller_test.go
- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
- pkg/controller/xdstest/fake_xdsclient.go
- pkg/controller/xdstest/fake_xdsserver.go
- pkg/nets/nets.go
- Abstract xds clients to simplify ut 
- Added handle workload tests
Fixes #
```release-note
```
> Added workload response handler tests

- README.md
> fix error link in readme

- docs/proposal/dns_resolve.md
typo fix
Fixes #
```release-note
```
> fix typos of dns resolver proposal

- api/v2/workloadapi/security/authorization_help.go
- pkg/auth/policy_store.go
- pkg/auth/policy_store_test.go
- pkg/auth/rbac.go
- pkg/auth/rbac_test.go
- pkg/controller/workload/cache/workload_cache.go
Fix the issue: a authorization deleted, the same namespace scoped authorization will be mis removed
Fixes #
```release-note
```
> Fix authPolicy remove

- daemon/manager/dump/dump.go
- daemon/manager/manager.go
- daemon/manager/version/version.go
- pkg/status/status_server.go
enhancement
add kmesh-daemon dump command
Fixes #
```release-note
```
> add kmesh-daemon dump command

- .github/workflows/main.yml
- .gitignore
- hack/run-ut.sh
> Enable go race detect

- pkg/cache/v2/cluster.go
- pkg/cache/v2/maps/cluster.go
- pkg/controller/ads/ads_controller.go
- pkg/controller/ads/ads_processor.go
- pkg/controller/ads/ads_processor_test.go
/kind bug
Fixes  https://github.com/kmesh-net/kmesh/issues/437
Fixes https://github.com/kmesh-net/kmesh/issues/440
1. Fix cluster leak after service deleted
2. Fix route leak after service deleted
3. And fix missing subscribe eds after reconnect
```release-note
```
> Bug fix on xds handler

- pkg/auth/rbac.go
- pkg/auth/rbac_test.go
- pkg/auth/xdp_auth_handler.go
- pkg/controller/client.go
1. Clarify byteorder transformation in Authz
2. Remove magic number in Authz
Fixes #323
```release-note
NONE
```
> Simplify byteorder transformation & remove magic number in Authz

- bpf/include/common.h
Add one of the following kinds:
/kind bug
https://github.com/kmesh-net/kmesh/issues/460
```release-note
```
> fix compile failed on openEuler 2203

- pkg/auth/policy_store.go
- pkg/auth/rbac.go
- pkg/controller/ads/ads_processor.go
- pkg/controller/client.go
- pkg/controller/workload/workload_controller.go
- pkg/controller/workload/workload_controller_test.go
- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
- pkg/controller/xdstest/fake_xdsserver.go
> Should send initial authz resources when reconnect

- .github/workflows/e2e.yml
- .github/workflows/main.yml
Fixes #467 
```release-note
```
> Split E2E test as a separate CI jobs

- bpf/kmesh/workload/sendmsg.c
/kind feature
Fixes #
```release-note
```
> optimization: normalized ADDR type

- pkg/controller/bypass/bypass_controller.go
- pkg/controller/bypass/bypass_test.go
Fixes #371 
```release-note
```
> add UT for bypass

- pkg/controller/client.go
- pkg/controller/controller.go
- pkg/controller/workload/workload_controller.go
- pkg/controller/workload/workload_controller_test.go
- pkg/controller/workload/workload_processor.go
/kind bug
Fix authz goroutine not started
Fixes #484
```release-note
NONE
```
> Fix authz goroutine not started

- go.mod
- pkg/cache/v2/cluster.go
- pkg/cache/v2/route.go
- pkg/controller/ads/ads_processor.go
- pkg/controller/ads/ads_processor_test.go
- pkg/controller/ads/cache.go
- pkg/controller/client_test.go
- pkg/controller/controller.go
- pkg/dns/dns.go
- pkg/dns/dns_test.go
/kind feature
To support DNS typed cluster in ads mode.
Here is the proposal: https://github.com/kmesh-net/kmesh/blob/main/docs/proposal/dns_resolve.md
Fixes #215 
```release-note
```
> Support dns resolution typed service

- hack/run-ut.sh
enhancement
support run specified unit test (#488)
Example:
```shell
make test TEST_TARGET=TestServer_getLoggerLevel
```
```release-note
```
> support run specified unit test (#488)

- pkg/constants/constants.go
- pkg/status/status_server.go
enhancement
merge log handlers (#498)
Examples:
Fixes #498
```release-note
```
> merge log handlers (#498)

- deploy/yaml/kmesh.yaml
enhancement
add missing flags to keep the same as helm deploy
Fixes #
```release-note
```
> keep the same as helm deploy

- .github/ISSUE_TEMPLATE/enhancement.md
enhancement can be more commonly used
> update issue label

- pkg/controller/controller.go
fix workloadController.run() not called error
Fixes #
```release-note
```
> fix workloadController.run() not called error

- hack/run-ut.sh
- pkg/status/status_server_test.go
enhancement
Add some uts for setting bpf log level
Fixes #
```release-note
```
> Add some uts for setting bpf log level

- daemon/manager/manager.go
- pkg/controller/bypass/bypass_controller.go
- pkg/controller/bypass/bypass_test.go
- pkg/controller/controller.go
- pkg/controller/manage/kmesh_manage.go
- pkg/controller/manage/kmesh_manage_test.go
enhance
Fixes #497 
```release-note
```
> cleanup stopch(#497)

- build/docker/kmesh.dockerfile
- hack/utils.sh
- kmesh.spec
- oncn-mda/cli_src/func/global.c
- oncn-mda/cli_src/func/switch.c
- oncn-mda/ebpf_src/sock_ops.c
- oncn-mda/include/data.h
- oncn-mda/include/macli.h
- oncn-mda/include/mesh_accelerate.h
modify oncn-mda to be compatible with kernel 6.6 
Fixes #
```release-note
```
> modify oncn-mda to be compatible with kernel 6.6

- oncn-mda/cli_src/func/global.c
- oncn-mda/cli_src/func/switch.c
- oncn-mda/include/macli.h
Add compilation macro for oncn-mda
Fixes #
```release-note
```
> Add compilation macro for oncn-mda

- bpf/kmesh/bpf2go/bpf2go.go
- test/e2e/baseline_test.go
- test/e2e/main_test.go
> Add missing copy right

- samples/fortio/fortio-header.yaml
- samples/fortio/fortio-route.yaml
- samples/fortio/fortio-v1-10-v2-90.yaml
- samples/fortio/netuils.yaml
> kmesh route samples

- bpf/kmesh/probes/metrics.h
- go.mod
- pkg/constants/constants.go
- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/metric_test.go
- pkg/controller/telemetry/utils.go
- pkg/controller/telemetry/utils_test.go
- pkg/controller/workload/workload_controller.go
Implementation of metric in kmesh observability
Fixes #320 
```release-note
```
> Kmesh Observability

- bpf/kmesh/probes/metrics.h
- go.mod
- pkg/constants/constants.go
- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/metric_test.go
- pkg/controller/telemetry/utils.go
- pkg/controller/telemetry/utils_test.go
- pkg/controller/workload/workload_controller.go
> [cherry-pick 0.4] Kmesh observability

- pkg/controller/workload/workload_hash.go
Fixes #534 
```release-note
```
> fix unexpected log

- pkg/controller/bypass/bypass_controller.go
- pkg/controller/bypass/bypass_test.go
Fix test failure found in https://github.com/kmesh-net/kmesh/actions/runs/9869244456/job/27252634097?pr=537
> Fix TestPodSidecarLabelChangeTriggersAddIptablesAction flake

- bpf/include/bpf_common.h
- bpf/kmesh/workload/sockops.c
Modifybpf map update to prevent potential bugs
Fixes #536 
```release-note
```
> Modifybpf map update to prevent potential bugs

- Makefile
/kind feature
Fixes #
```release-note
```
> modify kmesh version to v0.4.0

- docs/kmesh_deploy_and_develop_in_kind.md
documentation
add document for deploying and developing in kind
Fixes #
```release-note
```
> add document for deploying and developing in kind

- SECURITY.md
> add security.md for kmesh

- README.md
> add badge in readme

- pkg/controller/workload/workload_processor.go
Even if a workload is associated with a service, the workload can still be directly accessed.
Fixes #503
```release-note
```
> optimize workload update

- pkg/constants/constants.go
- pkg/controller/controller.go
- pkg/controller/manage/kmesh_manage.go
- pkg/controller/manage/kmesh_manage_test.go
- pkg/controller/security/manager.go
- pkg/controller/workload/workload_processor.go
kmesh secutity only manage pod managed by kmesh
Fixes #
```release-note
```
> kmesh security: pod manage

- deploy/helm/templates/daemonset.yaml
- deploy/yaml/kmesh.yaml
- samples/addons/prometheus.yaml
- samples/tcp-echo/tcp-echo-ipv4.yaml
- samples/tcp-echo/tcp-echo-ipv6.yaml
- samples/tcp-echo/tcp-echo.yaml
add configuration to collect kmesh metrics using Prometheus
a part of  #566 
```release-note
```
> add configuration to collect kmesh metrics using Prometheus

- pkg/controller/manage/kmesh_manage.go
fix pod management can not be canceled
Fixes #568 
```release-note
```
> fix pod management can not be canceled

- pkg/controller/manage/kmesh_manage.go
- pkg/controller/manage/kmesh_manage_test.go
/kind bug
waypoint should not managed by Kmesh
Fixes #
```release-note
```
> waypoint should not managed by Kmesh

- pkg/controller/manage/kmesh_manage.go
- pkg/controller/manage/kmesh_manage_test.go
/kind bug
Fixes #611 
```release-note
```
> [release 0.4.0]waypoint should not managed by Kmesh

- pkg/controller/bypass/bypass_controller.go
- pkg/controller/bypass/bypass_test.go
- pkg/controller/controller.go
- pkg/controller/manage/manage_controller.go
- pkg/controller/manage/manage_controller_test.go
> Bypass only for sidecar

- bpf/kmesh/probes/metrics.h
> update metric_key with direction & dst_port

- bpf/include/bpf_common.h
- bpf/kmesh/ads/cgroup_sock.c
- bpf/kmesh/workload/cgroup_sock.c
- bpf/kmesh/workload/sockops.c
> remove bypass from bpf prog

- bpf/kmesh/workload/sockops.c
- bpf/kmesh/workload/xdp.c
- pkg/auth/rbac.go
- pkg/auth/rbac_test.go
- pkg/auth/xdp_auth_handler.go
/kind bug
Fixes #653 
```release-note
```
> Fixed bug in bpf where IPv4 destination address was stored as IPv6

- pkg/controller/manage/manage_controller.go
- pkg/controller/manage/manage_controller_test.go
fix error log
Fixes #650
```release-note
```
> fix error log

- pkg/controller/manage/kmesh_manage.go
- pkg/controller/manage/kmesh_manage_test.go
fix error log that failed to enable Kmesh manage
Fixes #
```release-note
```
> [release-0.4] fix error log that failed to enable Kmesh manage

- pkg/controller/manage/manage_controller.go
- pkg/controller/manage/manage_controller_test.go
- pkg/utils/enroll.go
support ns manage donot need restart pod
Fixes #555 
```release-note
```
> Support ns manage donot need restart pod

- bpf/kmesh/workload/include/service.h
> Short circuit when svc endpoint count = 0

- bpf/include/bpf_common.h
- pkg/controller/manage/manage_controller.go
> fix data in bpfmap was cleared after kmesh restart in kind env

- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
/kind bug
Fixes  https://github.com/kmesh-net/kmesh/issues/683
```release-note
```
> [release-0.4] Fix namespaced waypoint service itself contains waypoint address

- pkg/status/api.go
- pkg/status/testdata/workload_configdump.json
Fixes partof https://github.com/kmesh-net/kmesh/issues/671
```release-note
```
> Sync up status API with workload api

- test/e2e/baseline_test.go
- test/e2e/main_test.go
after fixes #628, add coverage for e2e test for adding and removing ns granulariy waypoint.
Fixes #
```release-note
```
> enable e2e test case for ns granularity waypoint

- api/v2-c/workloadapi/workload.pb-c.c
- api/v2-c/workloadapi/workload.pb-c.h
- api/v2/workloadapi/workload.pb.go
- api/workloadapi/workload.proto
- pkg/controller/workload/cache/workload_cache.go
- pkg/controller/workload/workload_controller_test.go
- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
feature
Fixes #631 
```release-note
```
> Support hostname network

- deploy/helm/templates/l7-envoyfilter.yaml
- deploy/yaml/l7-envoyfilter.yaml
- test/e2e/baseline_test.go
- test/e2e/run_test.sh
/kind bug
fixes the failuire in waypoint processing non-HTTP tcp traffic.
Fixes #667
```release-note
```
> fix waypoint's processing of TCP

- .github/workflows/release-master.yaml
Sorry this is introduced by mistake
```release-note
```
> Update kmesh image

- test/e2e/main_test.go
- test/e2e/manage_test.go
Add basic test case for Kmesh manage.
Fixes part of #614
```release-note
```
> use dataplane label to manage workloads

- .github/workflows/release-master.yaml
- Makefile
- build/docker/dockerfile
> modify dockerfile

- pkg/controller/workload/workload_processor.go
- test/e2e/baseline_test.go
/kind bug
Fixes #691 
```release-note
```
> fix depolying ns and service waypoint in mixed manner and add related e2e test case

- .github/workflows/release-master.yaml
> Fix image tag

- pkg/controller/telemetry/utils.go
Fixes #738 
@YaoZengzeng 
```release-note
```
> match the meaning of Kmesh L4 metric with istio

- pkg/bpf/bpf_kmesh_workload.go
/kind bug
Fix: XDP prog duplicate when bpf filesystem mounted
Fixes #
```release-note
NONE
```
> Fix: XDP prog duplicate when bpf filesystem mounted

- kmesh_compile.sh
/kind bug
dockerfile cannot copy file without read permissions
Fixes #767
```release-note
```
> fix image ci bug:kmesh latest cannot use

- test/e2e/manage_test.go
Fixes #728
```release-note
```
> add e2e test case for cross ns access

- pkg/controller/telemetry/metric.go
/kind cleanup
Fixes #
```release-note
```
> make logs of metric clean up

- pkg/bpf/bpf_kmesh_workload.go
/kind bug
After restarting, multiple bpf_prog will be loaded. Fix this point and replace it with dynamic update.
Fixes #700
```release-note
```
> fix bpf prog double load 

- go.mod
- test/e2e/baseline_test.go
- test/e2e/main_test.go
- test/e2e/manage_test.go
add L4 Telemetry e2e case
Fixes #770 
```release-note
```
> E2e metric

- .github/workflows/e2e-ipv6-istio-1.23.yml
- .github/workflows/e2e-ipv6.yml
- .github/workflows/e2e-istio-1.23.yml
- .github/workflows/e2e.yml
- test/e2e/run_test.sh
Fixes #782
```release-note
```
> istio 1.23 for e2e

- test/e2e/baseline_test.go
Fixes #766
```release-note
```
> e2e test to include bookinfo as test application

- Makefile
Fixes #802
```release-note
```
> fix version display 

- .codecov.yml
> make codecov as an indication

- go.mod
- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/metric_test.go
- pkg/controller/telemetry/utils.go
- pkg/controller/telemetry/utils_test.go
Fixes #798 
```release-note
```
> Batch update metrics through prometheus API

- daemon/manager/manager.go
- daemon/manager/uninstall/uninstall.go
- daemon/options/cni.go
- go.mod
- pkg/cni/chained.go
- pkg/cni/chained_test.go
- pkg/cni/install.go
- pkg/cni/install_test.go
- pkg/cni/kubeconfig.go
Fixes part of #730 
```release-note
```
> update kubeconfig when token was updated

- pkg/controller/workload/bpfcache/backend.go
- pkg/controller/workload/bpfcache/endpoint.go
- pkg/controller/workload/bpfcache/frontend.go
- pkg/controller/workload/bpfcache/service.go
- pkg/controller/workload/cache/workload_cache.go
- pkg/controller/workload/cache/workload_cache_test.go
- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
Fixes #
```release-note
```
Assume the functuion is covered by existing tests, if not will supplement according codecov
> Refactor workload.Services compare and eliminate `shouldAddEndpoint`

- pkg/controller/manage/manage_controller.go
/kind cleanup
Fixes #
```release-note
```
> cleanup unuse parameters

- pkg/OWNERS
- test/OWNERS
> Add more approvers

- common/config/.golangci.yaml
- pkg/controller/security/caclient_test.go
- pkg/controller/security/manager_test.go
- pkg/controller/workload/workload_processor.go
- pkg/dns/dns.go
golangci lint has so many tools, by default all of them are enabled. Here we need to diable all and enable those we need explicitly
Fixes #
```release-note
```
> update golangci lint

- pkg/auth/rbac.go
- pkg/controller/telemetry/metric.go
> update confusing get workload logging

- hack/install-proto.sh
Fixes #837 
```release-note
```
> build: fix `make gen` failed on arm64.

- bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
/kind bug
Fixes #849 
```release-note
```
> fix ads deserial bug

- pkg/controller/ads/ads_processor.go
- pkg/controller/ads/ads_processor_test.go
- pkg/dns/dns.go
- pkg/dns/dns_test.go
Supersed https://github.com/kmesh-net/kmesh/pull/608
```release-note
```
> Fix dns memleak when dns cluster removed

- daemon/manager/manager.go
- daemon/options/bpf.go
- pkg/controller/client.go
- pkg/controller/client_test.go
- pkg/controller/controller.go
- pkg/controller/telemetry/metric.go
- pkg/controller/workload/workload_controller.go
- pkg/controller/workload/workload_processor_test.go
Added a switch for accesslog to be able to turn it on on demand
Fixes #857 
```release-note
```
> add a trigger for accesslog

- test/e2e/run_test.sh
Enable non-default cluster
Fixes #524 
```release-note
```
> Enable non-default cluster

- .github/workflows/e2e-ipv6-istio-1.23.yml
- .github/workflows/e2e-ipv6.yml
- .github/workflows/e2e-istio-1.23.yml
- .github/workflows/e2e.yml
- .github/workflows/main.yml
Fixes #880 
```release-note
```
> add github ci ignore path

- pkg/cache/v2/maps/authz.go
- pkg/cache/v2/maps/cluster.go
- pkg/cache/v2/maps/common.go
- pkg/cache/v2/maps/listener.go
- pkg/cache/v2/maps/route.go
Fixes #875
```release-note
```
> Prevent potential panic when object is nil or empty

- Makefile
For #894
Fixes #
```release-note
```
> [release-0.5] update VERSION

- .gitignore
- build.sh
- hack/utils.sh
- kmesh_compile.sh
> Fix build warning and remove docker pull explicitly

- Makefile
> update VERSION to 0.5.0

- Makefile
Reverts kmesh-net/kmesh#896
This should be on release-0.5
> Revert "update VERSION"

- ctl/main.go
- ctl/utils/utils.go
- ctl/waypoint/waypoint.go
- go.mod
Implement `kmeshctl waypoint` subcommand, so we could use it to better manage waypoints.
Fixes part of #821
```release-note
```
> `kmeshctl waypoint` framework

- bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
- bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.h
- pkg/bpf/bpf.go
- pkg/bpf/bpf_kmesh_l4_workload.go
/kind bug
Fixes #
```release-note
```
> fix slow restart in workload mode

- .github/workflows/e2e-ipv6-istio-1.23.yml
- .github/workflows/e2e-ipv6.yml
- .github/workflows/e2e-istio-1.23.yml
- .github/workflows/e2e.yml
- .github/workflows/main.yml
- build/docker/builder.dockerfile
- go.mod
This PR resolves https://github.com/kmesh-net/kmesh/issues/795 by upgrading the version of `go` to 1.23.2.
Fixes https://github.com/kmesh-net/kmesh/issues/795
```release-note
Upgrade go to 1.23.2
```
> upgrade golang to 1.23

- pkg/controller/workload/bpfcache/auth_policy.go
- pkg/controller/workload/bpfcache/backend.go
- pkg/controller/workload/bpfcache/endpoint.go
- pkg/controller/workload/bpfcache/frontend.go
- pkg/controller/workload/bpfcache/service.go
- pkg/controller/workload/workload_processor.go
Fix https://github.com/kmesh-net/kmesh/issues/954
```release-note
```
> Ignore key not exist error when delete bpf map

- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/metric_test.go
> if sourceworkload is nil, not print metrics

- test/e2e/run_test.sh
Fixes part of #930
```release-note
```
> install istioctl in tmp dir when running E2E tests

- MAINTAINERS.md
Fix project name misspelling in MAINTAINERS file
Fixes #
```release-note
```
> Fix MAINTAINERS file misspelling

- pkg/controller/client.go
/kind bug
Add clusterid in grpc stream context
Fixes #981 
```release-note
NONE
```
> add clusterid in grpc stream context

- test/e2e/run_test.sh
/kind bug
Fixes the typo
```release-note
```
> Fix the typo

- Makefile
> Static compile cni and ctl

- pkg/controller/ads/cache.go
- pkg/controller/ads/extensions/local_ratelimit.go
- pkg/controller/ads/extensions/local_ratelimit_test.go
> ut: fix local ratelimit code cause other failed.

- pkg/consistenthash/maglev/maglev.go
- pkg/controller/ads/cache.go
> fix lb_ospp bug and add ref

- hack/copyright-check.sh
- hack/copyright/copyright_scan_dir.json
- test/e2e/baseline_test.go
- test/e2e/gateway_test.go
- test/e2e/run_test.sh
Framework for managing ingress gateway instance and basic E2E test case for ingress gateway.
Fixes part of #1001
```release-note
```
> E2E test for ingress gateway

- bpf/kmesh/ads/include/filter.h
- bpf/kmesh/ads/include/local_ratelimit.h
fix ratelimit compile failed on oe.
Fixes #
```release-note
```
> Ratelimit bug fix.

- deploy/yaml/kmesh.yaml
> Update --profiling flag in kmesh yaml

- pkg/controller/telemetry/map_metric.go
Fix https://github.com/kmesh-net/kmesh/issues/1036 
```release-note
```
> Fix kmesh_map_count_total label

- bpf/kmesh/probes/probe.h
- bpf/kmesh/workload/cgroup_sock.c
- bpf/kmesh/workload/include/service.h
> Add more debug log

- samples/addons/prometheus.yaml
> update prometheus image version

- bpf/kmesh/workload/xdp.c
/kind bug
Fixes #1053
```release-note
```
> fix bpf load failed in Ubuntu

- bpf/include/bpf_common.h
- bpf/kmesh/ads/include/ctx/sock_ops.h
/kind bug
Fixes https://github.com/kmesh-net/kmesh/issues/1050
```release-note
```
> fix sockops prog load failed in Ubuntu kernel-enhanced env

- pkg/bpf/bpf.go
- pkg/bpf/bpf_test.go
- pkg/status/status_server.go
> Provides functions to get and update kmeshconfigMap.

- pkg/controller/workload/cache/endpoint_cache.go
- pkg/controller/workload/cache/endpoint_cache_test.go
- pkg/controller/workload/workload_processor.go
> Optimize service lb policy update

- .github/workflows/e2e-ipv6-istio-1.24.yml
- .github/workflows/e2e-istio-1.24.yml
> add E2E test for istio 1.24 to CI

- bpf/kmesh/workload/xdp.c
Changed log level for authz_offload=0 case to avoid keep reporting logs
Fixes #
```release-note
```
> Changed log level for authz_offload=0 case

- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/utils.go
**Which issue(s) this PR fixes**
a part of #1033 
```release-note
```
> Improvement of metriclabels removal capability at workload granularity

- pkg/controller/telemetry/bpf_prog_metric_test.go
- pkg/controller/telemetry/map_metric_test.go
> map_mertic and bpf_prog_metric test

- bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
- pkg/cache/v2/listener_test.go
/kind bug
Fixes https://github.com/kmesh-net/kmesh/issues/1064
```release-note
```
> fix repeat string field proc

- ctl/authz/authz.go
- docs/ctl/kmeshctl.md
- docs/ctl/kmeshctl_authz.md
> fix kmeshctl auth command description

- daemon/options/bpf.go
- deploy/charts/kmesh-helm/values.yaml
- deploy/yaml/kmesh.yaml
- pkg/controller/controller.go
/kind cleanup
Fixes #1071
```release-note
```
> Remove enable-bpf-log from the startup parameters

- bpf/kmesh/workload/sockops.c
- bpf/kmesh/workload/xdp.c
> remove spammy log from authz 

- bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
- bpf/include/bpf_common.h
- bpf/include/common.h
- bpf/include/inner_map_defs.h
- bpf/kmesh/workload/include/workload_common.h
> add support for PROTOBUF_C_TYPE_BYTES

- bpf/include/bpf_log.h
- bpf/include/map_config.h
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkload_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupsockworkloadcompat_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkload_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshsockopsworkloadcompat_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshxdpauth_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshxdpauthcompat_bpfel.go
- bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfeb.go
- bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfel.go
- bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfeb.go
- bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfel.go
- pkg/controller/controller.go
- pkg/logger/logger.go
> Refact: Bpf log reader start

- pkg/status/status_server.go
/kind cleanup
Fixes #
```release-note
```
> delete unnecessary kmeshctl handlers

- bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockops_bpfeb.go
- bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockops_bpfel.go
- bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockopscompat_bpfeb.go
- bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockopscompat_bpfel.go
- pkg/bpf/ads/loader_enhanced.go
- pkg/bpf/ads/sock_ops.go
> update mapname in kernelnative enhanced

- bpf/kmesh/workload/include/backend.h
> Skip matching svc again in backend_manager

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/question.md
Add `istio version`, `kmesh mode` and `kernel version` in bug report and question issues.
It allows others to clarify environmental information more quickly.
Fixes #
```release-note
```
> update issue template

- bpf/kmesh/ads/include/config.h
- bpf/kmesh/ads/include/ctx/sock_addr.h
- bpf/kmesh/ads/include/ctx/sock_ops.h
- bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockops_bpfeb.go
- bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockops_bpfel.go
- bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockopscompat_bpfeb.go
- bpf/kmesh/bpf2go/kernelnative/enhanced/kmeshsockopscompat_bpfel.go
- bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfeb.go
- bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsock_bpfel.go
- bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfeb.go
- bpf/kmesh/bpf2go/kernelnative/normal/kmeshcgroupsockcompat_bpfel.go
- pkg/bpf/ads/sock_connection.go
- pkg/bpf/ads/sock_ops.go
- pkg/bpf/utils/pin.go
/kind bug
1. start failed in enhanced kernel-native mode
2. fix workload tail_call wrong pin in SetMapPinType, move it in SockConnWorkload attach 
Fixes #1099
```release-note
```
> fix start failed in enhanced kernel-native mode

- pkg/bpf/utils/pin.go
- pkg/bpf/workload/xdp.go
> Clean dead code in xdp loader

- bpf/kmesh/workload/cgroup_sock.c
- bpf/kmesh/workload/include/backend.h
- bpf/kmesh/workload/include/endpoint.h
- bpf/kmesh/workload/include/frontend.h
- bpf/kmesh/workload/include/service.h
This is the first step to provide more readable and meaningful log. 
The following work should to design some Format String to represent svc id, etc. And to do efficient replace in userspace.
Fixes #
```release-note
```
> better bpf logging

- bpf/deserialization_to_bpf_map/deserialization_to_bpf_map.c
/kind bug
Fixes #
```release-note
```
> fix Invalid size: -1

- pkg/bpf/bpf.go
KmeshBpfConfig is now initialised every time Kmesh is restarted. This causes the debug mode for bpf-log to need to be re-enabled each time. 
Now we optimised the handling of kmeshConfigMap creation to avoid initialising it every time you reboot.
Fixes #1120 
```release-note
```
> Optimised kmeshConfigMap to avoid initialising it every time kmesh reboot.

- bpf/kmesh/workload/cgroup_sock.c
Fixes https://github.com/kmesh-net/kmesh/issues/1126
```release-note
```
> remove spammy log cause by unknown service access

- bpf/kmesh/workload/include/backend.h
/kind bug
```sh
time="2024-12-25T09:22:35Z" level=info msg="[BACKEND] DEBUG: svc -63195162 dnat to [10.244.0.12:15019]\n" subsys=ebpf
```
Fixed this log showing negative numbers.
Fixes #
```release-note
```
> fix service DEBUG log report negative number

- pkg/controller/manage/manage_controller.go
> Fix after kmesh daemon restart, xdp should be re linked

- pkg/controller/workload/workload_processor.go
Modified log handling in workload_processor to avoid repeated descriptions of error messages.
Fixes #
```release-note
```
> Modified log handling in workload_processor

- pkg/nets/nets_test.go
change TestCompareIpByte to table driven test.
Fixes #
```release-note
```
> change TestCompareIpByte to table driven test

- pkg/controller/workload/workload_processor.go
- pkg/controller/workload/workload_processor_test.go
/kind bug
handle service and workload conflicts in the frontend map of serviceEntry cases.
Fixes #1149
```release-note
```
> handle service and workload conflicts in the frontend map

- hack/run-ut.sh
> make sure uts in different pkg cannot be run in parallel

- hack/run-ut.sh
Clean up docker properly when ut fails.
And remove function `prepare`.
Fixes #1154 
```release-note
```
> Clean up docker properly when ut fails

- README.md
add meeting in readme
Fixes #
```release-note
```
> add meeting in readme

- Makefile
a part of #1171
```release-note
```
> [release-1.0] update the VERSION to 1.0.0 in Makefile

- Makefile
Added out to specify the name after kmeshctl build.
Fixes #
```release-note
```
> Can specify the out name for kmeshctl

- Makefile
> [release-1.0] Change the version to v1.0.0-rc.0 in the makefile

- .github/workflows/release-master.yaml
- .github/workflows/release.yml
- Makefile
- hack/update-version.sh
Added script that automatically updates kmesh VERSION based on github tags.
Fixes #
```release-note
```
> add scripts to change kmesh version automatically

- pkg/bpf/ads/loader_enhanced.go
/kind bug
Fixes #
```release-note
```
> fix kernel_enhanced lack of pkg general

- Makefile
> bump version to 1.1-dev

- README.md
> Update meeting  in README.md

- bpf/kmesh/probes/tcp_probe.h
Fix the typo
Fixes #1221
None
```release-note
```
> chore: solved contruct_tuple typo #1221

- docs/ctl/kmeshctl.md
- docs/ctl/kmeshctl_authz.md
- docs/ctl/kmeshctl_authz_disable.md
- docs/ctl/kmeshctl_authz_enable.md
- docs/ctl/kmeshctl_authz_status.md
Modify the kmeshctl documentation according to make gen
#1239 is blocked by this problem
```release-note
```
> Modify the kmeshctl documentation according to make gen

- OWNERS
add LiZhenCheng9527 to OWNERS and alphabetized the owners' list
Fixes #
```release-note
```
> add LiZhenCheng9527 to OWNERS

- bpf/kmesh/ads/include/route_config.h
Fixes #553
```release-note
```
> fix bookinfo issue 553

- ctl/waypoint/waypoint.go
/kind bug
Fixes #1287 
```release-note
```
> fix getKmeshWaypointImage tag

- pkg/controller/workload/workload_processor.go
- test/e2e/gateway_test.go
/kind bug
Fix possible e2e panic and add service name in warning of service exceeded max port
```release-note
```
> fix possible e2e panic and update maxportnum warning

- bpf/include/bpf_log.h
/kind cleanup
Introduced spammy log when refactoring bpf config via global variable
Fixes #
```release-note
```
> Remove spammy log

- pkg/bpf/bpf.go
global variables cannot be shared among different bpf progs, so we should update all
Fixes #
```release-note
```
> Fix bpf log level

- test/e2e/run_test.sh
/kind cleanup
Fixes #
```release-note
```
> remove deprecated flag `--enable-bpf-log` in e2e test

- .github/workflows/e2e-ipv6-istio-1.23.yml
- .github/workflows/e2e-ipv6-istio-1.24.yml
- .github/workflows/e2e-ipv6.yml
Fixes https://github.com/kmesh-net/kmesh/issues/1301
```release-note
```
> update ubuntu 2404

- bpf/kmesh/bpf2go/dualengine/kmeshcgroupskb_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupskb_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupskbcompat_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupskbcompat_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfel.go
- bpf/kmesh/workload/cgroup_skb.c
/kind bug
https://github.com/kmesh-net/kmesh/actions/runs/14511555828/job/40711233928
Fixes #
```release-note
```
> fix build error：fatal error: 'encoder.h' file not found

- bpf/kmesh/bpf2go/dualengine/kmeshcgroupskb_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupskb_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupskbcompat_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshcgroupskbcompat_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshsendmsg_bpfel.go
- bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfeb.go
- bpf/kmesh/bpf2go/dualengine/kmeshsendmsgcompat_bpfel.go
- bpf/kmesh/workload/cgroup_skb.c
- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/metric_test.go
/kind bug
Fixing updating connOpened metric for the conn report at intervals, added unit test to confirm the change
Fixes #1307
No
```release-note
```
> fix: Updating connOpened metric for the conn report at intervals #1307

- docs/kmesh_commands-zh.md
- docs/kmesh_commands.md
fix kmesh daemon commands description
Fixes #
```release-note
```
> fix kmesh daemon commands description

- CONTRIBUTING.md
- hack/format.sh
added gomft in makefile
Fixes #1323
```NONE
```
> rfac: added gomft in makefile

- pkg/controller/workload/workload_processor.go
… serviceEntry
/kind bug
a part of #1339 
```release-note
```
> fix workload processer panic if newWorkload addresses is nil when add serviceEntry

- test/e2e/baseline_test.go
Fixes #492
```release-note
```
> e2e test for l4 authorization

- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/metric_test.go
- test/e2e/baseline_test.go
/kind bug
fix: values is not updated in tcp_conn map
Fixes #1341
```NONE
```
> fix: values is not updated in tcp_conn map #1341

- README.md
> Update quick-start link

- pkg/status/status_server.go
/kind bug
enabling enableConnMetric knob at monitoring handler
Fixes #1366
```release-note
```
> fix: enableConnMetric knob at monitoring handler

- docs/proposal/tcp_long_connection_metrics.md
- pkg/controller/telemetry/accesslog.go
- pkg/controller/telemetry/metric.go
/kind bug
Fixes https://github.com/kmesh-net/kmesh/issues/1367
```release-note
```
> Skip output accesslog on connection establishment

- test/e2e/baseline_test.go
> e2e for l4 auth

- pkg/controller/telemetry/accesslog.go
- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/metric_test.go
Fixes #1370
```release-note
```
> Fix regression by socket tuple when c/s deployed in same node

- pkg/controller/telemetry/metric.go
- pkg/controller/telemetry/metric_test.go
ut coverage for same src/dst but different direction
Fixes #1384 
```NONE
```
> chore: ut coverage for same src/dst but different direction

- samples/addons/grafana.yaml
- samples/addons/kmesh_performance-monitoring.json
/kind bug
Because after the #1007  changes, didn't change metrics name in grafana.
Now fix it.
Fixes #
```release-note
```
> Changed the metric name of grafana to match the metric name reported by kmesh

- pkg/controller/manage/manage_controller.go
/kind bug
Fixes #1357
```release-note
```
> fix flaky of `TestCrossNamespace`

- OWNERS
> add YaoZengzeng as owner

- bpf/include/bpf_common.h
- test/e2e/run_test.sh
Fixes #1390
```release-note
```
> output kmesh log when e2e test failed

- pkg/cache/v2/listener_test.go
- pkg/controller/ads/ads_processor_test.go
- pkg/controller/ads/convert_filter_test.go
- pkg/controller/telemetry/metric_test.go
- pkg/controller/workload/bpfcache/endpoint_test.go
- pkg/controller/workload/cache/waypoint_cache_test.go
- pkg/controller/workload/workload_processor_test.go
- pkg/status/status_server_test.go
/kind bug
Fixes #1420
```release-note
NONE
```
> Fix:  wrong arg order of testify/assert

- docs/ebpf_unit_test_zh.md
Using the same markdownlint version as in the lint workflow (markdownlint-cli2 v0.18.1 (markdownlint v0.38.0)), fix the errors reported by markdownlint-cli2.
Fixes #
```release-note
```
> fix markdownlint error

- .gemini/config.yaml
The dedault thereshold is medium, which seems too spammy
Fixes #
```release-note
```
> Tune gemini review severity threshold to HIGH

- ctl/waypoint/waypoint.go
- docs/ctl/kmeshctl_waypoint_apply.md
> fix an error of kmeshctl waypoint
